### ISSUE TITLE
Robomongo crashes when using 'delete' JS keyword or removing/retrieving by key 

### ISSUE THREAD

**Issue by dmumladze** [Studio3T/robomongo#1096]
The error happens when I try to use the delete keyword or remove/retrieve by the key for the first time anywhere in the script, but not after relaunching app and running the script again.

**From the Windows Event Viewer the error is following**
Faulting application name: Robomongo.exe, version: 0.9.0.0, time stamp: 0x56d86680
Faulting module name: Robomongo.exe, version: 0.9.0.0, time stamp: 0x56d86680
Exception code: 0xc0000005
Fault offset: 0x0000000000608e94
Faulting process id: 0xbf4
Faulting application start time: 0x01d1b126022192bd
Faulting application path: C:\Program Files\Robomongo 0.9.0-RC8\Robomongo.exe
Faulting module path: C:\Program Files\Robomongo 0.9.0-RC8\Robomongo.exe
Report Id: 79f93cdc-1d19-11e6-91ee-0050569837dd

**The script I'm trying to run is following**
function getClients(clients) {
    var map={};
    if (clients != null) {
        for (var i=0; i<clients.length; i++) {
            var arr=map[clients[i].srcsysid];
            if (!arr) {
                arr=[];
                map[clients[i].srcsysid]=arr;
            }
            arr[arr.length]=clients[i];
        }
    }
    return map;
}

var count=db.contacts.find({"links.status":65,"clients.enddt":{$exists:true}}).count();
var skip=0;
var limit=1000;

while (skip<=count) {  
    db.contacts.find({"links.status":65,"clients.enddt":{$exists:true}},{"links":1,"clients":1}).skip(skip).limit(limit).forEach(function(c) {  
        var map=getClients(c.clients); //get map with srcsysid key
        for (var i=0; i<c.links.length; i++) {
            if (c.links[i].status === 73) {
                delete map[c.links[i].srcsysid]; //remove clients for inactive contact
            }  
        }
        var tracked={}; //keep track of clients with end date
        for (var k in map) {
            var clients=map[k];
            if (!clients) {
                continue;
            }
            for (var i=0; i<clients.length; i++) {
                var client=clients[i];
                if (client.enddt !== undefined) { 
                    tracked[client.srcsysid]=client; //track ones with end date
                } else if (tracked[client.srcsysid]) {
                    delete tracked[client.srcsysid]; //untrack if there's no end date
                }
            }
        } 
        for (var k in tracked) {
            var client=tracked[k];
            if (client) {  
                print('db.contacts.update({"_id":'+c._id+',"clients":{$elemMatch:{"type":"'+client.type+'","clientid":"'+client.clientid+'"}}},{$unset:{"clients.$.enddt":""}},{multi:true})');
            }
        }
    });
    skip+=limit;
}

**Comment by juliashibalko** [comment]
Hi @August2008 , thank you for detailed report! Let me try to reproduce the issue and share my results with you.
