### ISSUE TITLE
0.9.0-RC8 doesn't load .mongorc.js file in Windows

### ISSUE THREAD

**Issue by zatnekitel** [Studio3T/robomongo#1099]
I created .mongorc.js file under my home directory in Windows (C:\Users\myuser) and enabled the option from the menu to load the file upon start. However, when I open any new shell I don't see the changes that were supposed to be done reflected.

This is the line I had in .mongorc.js:
`db.getMongo().setReadPref('secondaryPreferred');`

I connect to a DB using a SSH tunnel and after opening a shell, I was expecting to see `secondaryPreferred` after executing the command `db.getMongo().getReadPrefMode()` but is not happening.

In older versions (0.8.X) it used to work fine.

**Comment by simsekgokhan** [comment]
Hi @zatnekitel, we have tried to reproduce the issue, but it worked for us. Can you please specify Windows version? And you can also double check if the script is located in correct directory (i.e. under correct user).

Best Regards,
Gokhan

**Comment by zatnekitel** [comment]
I use Windows 10 and the file is under the right user home directory.

Is there any environment variable that might be needed?

**Comment by simsekgokhan** [comment]
No additional variables are needed. I tried with windows 10, it also worked. 
Can you make sure ".mongorc.js" does not have different file extension i.e. ".mongorc.js.txt", when you create a file on Win 10, it creates with .txt extension by default and you do not see that extension.
To see full file extension:
File Explorer -> Change Folder and Search Options 0 -> View tab -> remove tick on "Hide extensions for known file types"

**Comment by tincapo** [comment]
Hi guys, I have exactly the same issue. The .mongorc.js doesn't get loaded. I've checked the file extension, I've restarted the program as administrator as well and I can't see any reason it is not happening.

**Comment by zatnekitel** [comment]
My file had the .txt extension indeed. After removing it, it worked as expected. Thanks!

**Comment by simsekgokhan** [comment]
Hi,
@zatnekitel , glad to hear that it works now :)
@tincapo, can you please let us know your OS version and which directory the script is located?

**Comment by juliashibalko** [comment]
Hi @tincapo! Coulld you please try to reproduce issue once again? If it's still replicated, it would be helpful to attach more info so we can investigate the problem.
Thanks in advance!
