### ISSUE TITLE
Robomongo 0.9.0-RC8 crashing often.

### ISSUE THREAD

**Issue by treeliker** [Studio3T/robomongo#1113]
When ever i update a record in database and click the record again for verifying, it is crashing. Like, i save something and click a record, it crashes. 

I have to reopen again, it takes 23 seconds for going to table again. It wastes so much time. Everyday it crashes some 7-10 times. It reduces our productivity so much. Even if it saves quickly it takes me to start of the table, i have to navigate again.

Also 50 records are displayed. I have to change it to longer values to go to it again.

We can't do anything quickly or comfortably, so required.

So much waste of time. Kindly give fixes. Thanks.

**Comment by juliashibalko** [comment]
@treeliker Thank you for reporting issue. Could you please specify OS version, any crash reports and other details to help us with bug replicating? Thanks in advance!

**Comment by treeliker** [comment]
@juliashibalko 

Windows 7 Ultimate , 64 bit system, 
![robomongo crash report](https://cloud.githubusercontent.com/assets/19971181/16112407/cd68782a-33d4-11e6-866d-bf9ac7300adb.jpg) .

**Comment by juliashibalko** [comment]
@treeliker thank you, and just one more thing. Could you please expand "View problem details" and send copy to us?

**Comment by shivajivarma** [comment]
When ever i tried to click 'open' option in menu, it crashes (in Windows 10)
![untitled](https://cloud.githubusercontent.com/assets/1388742/20163212/b6220e32-a720-11e6-87ee-dd246b5e8d9d.png)

**Comment by juliashibalko** [comment]
Hi @treeliker and @shivajivarma! Could you please check issue with Robo3T 1.1 if possible? As I didn't manage to reproduce the problem under Windows 7 and 10.
Please see new release here https://robomongo.org/download.

**Comment by shivajivarma** [comment]
@juliashibalko: Thanks for letting me know. Its working fine on Robo 3T 1.1

**Comment by juliashibalko** [comment]
@shivajivarma thanks a lot! Closing this issue as fixed
