### ISSUE TITLE
Show stats popup again when hovering with mouse on a collection

### ISSUE THREAD

**Issue by pgp** [Studio3T/robomongo#1122]
As the title says, this is a very useful feature (especially when working with several collections) which has been missing since Robomongo 0.9.0 RC4. It would be comfortable to add it again.

**Comment by simsekgokhan** [comment]
Hi @pgp, thanks for your interest in Robomongo, we agree and we have already put this into our wishlist. Warm regards.

**Comment by gauravkalal** [comment]
Hi @simsekgokhan ,
Can you please let me know in robomongo version 0.8, on hovering over the collection is show size. which size is this? is ir storage size or Size parameter of stats() function?

**Comment by simsekgokhan** [comment]
Hi @gauravkalal, sure, it should show the "size" parameter.

**Comment by juliashibalko** [comment]
![image](https://cloud.githubusercontent.com/assets/16773195/19068300/ce8a817e-8a2a-11e6-9df1-ef9a101dbf61.png)
