### ISSUE TITLE
Not Able to instal Qt5 on my linux 

### ISSUE THREAD

**Issue by Rohitverma47** [Studio3T/robomongo#1132]
Hi Team,

I am facing issue to to set up RoboMongo , with pre-requisites list qt5.5 is required .
Following is my current qtchooser

ubuntu@ip-10-10-10-10:~/David$ qtchooser -print-env
QT_SELECT="default"
QTTOOLDIR="/usr/lib/x86_64-linux-gnu/qt5/bin"
QTLIBDIR="/usr/lib/x86_64-linux-gnu" 

ubuntu@ip-10-10-10-10:~$ qtchooser -l
5
default
qt5-x86_64-linux-gnu
qt5

what exactly is missing or where am i going wrong ?

**Comment by simsekgokhan** [comment]
Hi @Rohitverma47, we will try to help, way of doing it is: 

1. Go to http://download.qt.io/archive/qt/5.5/5.5.1/
2. Download, run and install qt-opensource-linux-x64-5.5.1.run
3. After successful installation you should have /path/to/qt-5.5.1/5.5/gcc_64 

More information for installing is here:
https://wiki.qt.io/Install_Qt_5_on_Ubuntu

Please Let us know how it went.

**Comment by Rohitverma47** [comment]
@simsekgokhan I did tried running this file but it gave an error
QXcbConnection: Could not connect to display
Aborted (core dumped)

Any help please

**Comment by Rohitverma47** [comment]
Iam on step3 of BUILD ROBOMONGO but when i run this command (bin/configure )
![robo](https://cloud.githubusercontent.com/assets/19685453/17054195/8179da7e-5023-11e6-9b35-abf4f96fdd2d.PNG)

**Comment by Rohitverma47** [comment]
and when i open CMakeError.log it is like
![error](https://cloud.githubusercontent.com/assets/19685453/17054264/e582f0d2-5023-11e6-9d8a-d4cfa2d5361c.PNG)

**Comment by simsekgokhan** [comment]
Hi, currently we are doing transition to Qt 5.7 (High DPI support),

**Comment by Rohitverma47** [comment]
what should i do any other way ?

**Comment by simsekgokhan** [comment]
Hi, currently we are doing transition to Qt 5.7 (High DPI support), I suggest to wait the end of milestone (around a week) for successful build. You can monitor the milestone here:

https://github.com/paralect/robomongo/milestone/14

-----------
For now, you can try installing Qt5.7. You will have to comment out 
```
robomongo\cmake\RobomongoInstall.cmake
Line 91:         #QGtk2ThemePlugin
```
And run configure script again.

**Comment by Rohitverma47** [comment]
and the link that you provided me before for download QT http://download.qt.io/archive/qt/5.5/5.5.1/
when i run it it shows 
![capture2](https://cloud.githubusercontent.com/assets/19685453/17054962/8c994d5a-5027-11e6-87b5-58c0ae16517a.PNG)

**Comment by Rohitverma47** [comment]
used these commands to install QT
sudo apt-add-repository ppa:beineri/opt-qt551-trusty
sudo apt-get update
sudo apt-get install qt-latest

**Comment by Rohitverma47** [comment]
I guess it is not working it is because that QT is not installed properly.
please provide me a proper link for that

**Comment by simsekgokhan** [comment]
I also think Qt is not properly installed and the problem seems to be you are using Ubuntu server version; we do our development on desktop environments. Next step might be finding a way to install Qt on command line. Also can you specify your purpose of building a desktop program like Robomongo in a server? (assuming you have ubuntu server)

**Comment by Rohitverma47** [comment]
yes we are using the Ubuntu Server to have a GUI for mongoDB.
so can you provide a link from which you can deploy QT5.5. successfully with target location e.g /opt/xyz... for server or desktop version. : so that we can easily install robomongo prerequisites. (P.S this is what we tried, but ended up with lots of issue, so installed QT directly.)

**Comment by Rohitverma47** [comment]
will get back to you shortly
