### ISSUE TITLE
robomongo windows crashes everytime when connection problems

### ISSUE THREAD

**Issue by henning** [Studio3T/robomongo#1150]
It seems like Robomongo 0.9.0 rc9 is crashing everytime when some kind of connection problem, even with wrong password etc occurs.

I get a Windows System dialog then, telling me the software is not working properly, and that its closed now.

I'm just a forced windows user , so my knowledge debugging windows problems and finding logs is limited. If you need me to run any test or collect any other output, please advise and Ill do what I can.

**Comment by juliashibalko** [comment]
@henning thank you for reporting. We are sorry for that! To help us with replicating could you please share your Windows version and if you have some free minutes, check this issue under previous Robomongo version (e.g. 0.9.0 - RC8)? 
Thanks in advance!

**Comment by juliashibalko** [comment]
https://github.com/paralect/robomongo/issues/1113

**Comment by DeepzSandra** [comment]
Hi,

I am using Robomongo 0.9.0 rc9 is crashing everytime how to slove this issues.
can u pls anybody tell me..

**Comment by simsekgokhan** [comment]
Hi @DeepzSandra, thanks for reporting the problem.

Can you please create a new ticket for your problem? https://t.co/axxRBDnKjL
Please also include your OS version, mongodb version, and condition (or steps) to reproduce this crash.
Crash logs are also required.

**Comment by henning** [comment]
Maybe it's the same crash?

But she should probably first trey a current version instead of reporting a bug in a super outdated version...

I am sorry that I cannot give you more info about my problem anymore - I'm, not in that customer project anym ore that forced me to use Windows.

But in that team it was a very well known problem that Robomongo crashed when using wrong login credentials, it should be easy to reproduce if it still exists. 

Othwerwise, you can close this, as I am not interested anymore, and cannot help due to unavailability of Windows ;)
