### ISSUE TITLE
Timestamp value is represented incorrectly (All versions)

### ISSUE THREAD

**Issue by dmumladze** [Studio3T/robomongo#1159]
This issue has been spotted in all version and reported for version 8 previously. The issue is in mongo shell it's Timestamp(1454752004, 743), but Robomongo displays it as Timestamp(6248112280970461, 743), which is exactly 4294967.296 times more than what it's suppose to be.

**Comment by juliashibalko** [comment]
@August2008 thanks for reporting! I managed to reproduce the issue. We will fix it during the next releases as now we are working on new Robomongo version with SSL feature. We will get back to you with any news!

**Comment by juliashibalko** [comment]
https://github.com/paralect/robomongo/issues/501

**Comment by dmumladze** [comment]
This is still not fixed as of 0.9.0.

**Comment by simsekgokhan** [comment]
Hi @dmumladze , we are really sorry for delay. We have been snowed under for some time to deliver some critical features. We delivered SSL and now we are focused on delivering Replica Sets and Export/Import asap. This ticket is tagged as "major", we will provide a fix as soon as we have a chance.

**Comment by simsekgokhan** [comment]
Also, original ticket #501 is tagged as "high vote" which makes it more likely to be fixed sooner than other issues.

**Comment by dmumladze** [comment]
In the meantime the workaround to show correct date is to divide by 4294967.296:

print(new Date(Timestamp(6363665786204061/4294967.296, 2).t/1000))

**Comment by simsekgokhan** [comment]
@dmumladze , thanks a lot for sharing. Best Regards.

**Comment by simsekgokhan** [comment]
Hi @dmumladze ,
There are some fixes related to Timestamp type on latest release Robomongo 1.0.
I hope it will solve your problem:
https://robomongo.org/download
http://blog.robomongo.org/robomongo-1-0/ -> section "c. Bug fixes"
