### ISSUE TITLE
Connecting to replica sets

### ISSUE THREAD

**Issue by munimkazia** [Studio3T/robomongo#116]
One fairly simple feature which should be useful to a lot of us is the option to connect to multiple servers which are a part of a replica set.  
Adding the different servers addresses separated by comma in the server address field doesn't seem to work.

**Comment by m-vdb** [comment]
+1

**Comment by egorpushkin** [comment]
+1

**Comment by kmargaritis** [comment]
:+1:

**Comment by deusofnull** [comment]
+1!!!

**Comment by Rewt0r** [comment]
+1

**Comment by mtrtm** [comment]
This is so effing annoying.  This was sooooo close to being funded, and now I look at the 'magic' backlog and it is less than half funded.  HOW DOES THAT WORK???  HOW MUCH TO FIX THIS?  If it isn't ridiculous I might be able to get my company to fund it.  Or damn, make a Visual Studio project that actually builds or update your documentation to make it easy for people to build/modify your project.  This change is literally a 5 minute change if you have the project already up and running.

**Comment by Rewt0r** [comment]
Good luck with that, this issue: https://github.com/paralect/robomongo/issues/520 has been funded for over 2 months and isn't done nor can I see it being worked on in the source.

**Comment by ulpian** [comment]
exactly, surely this should be an easy fix

**Comment by zylo47** [comment]
So is this project dead then?

**Comment by ulpian** [comment]
no idea

**Comment by petergyu** [comment]
Thank you guys for all your hard work, Robomongo is amazing! I think it is the best MongoDB browser out there. The one main feature that it's missing is not being able to connect to Replica Sets. I'm forced to use other MongoDB browsers like MongoHub but I'd much rather use Robomongo. I see that it's scheduled for 0.9.0. Thank you, I look forward to this release!

**Comment by joncursi** [comment]
:+1:

**Comment by michaelpurnell** [comment]
+1

**Comment by ApfelUser** [comment]
+1

**Comment by ianaz** [comment]
+1!!!! C'mon guys!!!

**Comment by gnetdev** [comment]
+1!!!

**Comment by tukaaa** [comment]
+1

**Comment by emmekappa** [comment]
+1

**Comment by feltocraig** [comment]
+1

**Comment by rfink** [comment]
+1

**Comment by iiSeymour** [comment]
+1

**Comment by Karnifexx** [comment]
+1

**Comment by Maikol** [comment]
+1

**Comment by Left47** [comment]
+1

**Comment by stinkyfingers** [comment]
+1

**Comment by benox3** [comment]
+1

**Comment by bbenzikry** [comment]
+1

**Comment by alexeypankov** [comment]
+1

**Comment by redtree1112** [comment]
+1

**Comment by ethiffeault** [comment]
+1

**Comment by joshmadewell** [comment]
+1

**Comment by derekshi** [comment]
+1

**Comment by motomux** [comment]
+1

**Comment by SargTeX** [comment]
+1

**Comment by martoo6** [comment]
+1 with sugar on top

**Comment by letscreate** [comment]
+1

**Comment by FunkyMJ** [comment]
+1 Thanks for working on it stennie

**Comment by arjanvdbos** [comment]
+1

**Comment by darxtar2005** [comment]
+1

**Comment by mpint** [comment]
+2

**Comment by MicheleBertoli** [comment]
+1

**Comment by ar1hur** [comment]
+1

**Comment by yadvendar** [comment]
+1

**Comment by JamesMGreene** [comment]
:+1:

**Comment by vincenthuynh** [comment]
+1

**Comment by fijimunkii** [comment]
:+1:

**Comment by breadbaker** [comment]
+1

**Comment by wzalazar** [comment]
+1

**Comment by maximilianschmid** [comment]
+1

**Comment by Dave1704** [comment]
+1

**Comment by kornakar** [comment]
+1

**Comment by loris** [comment]
+1

**Comment by JasonKDarby** [comment]
+1

**Comment by josuemma** [comment]
+1

**Comment by nodesocket** [comment]
:+1: when will replica set's be supported? `0.9.X`?

**Comment by LeoHuckvale** [comment]
+1

**Comment by connollyst** [comment]
+1 =)

**Comment by MichaelJCole** [comment]
+1 on 0.8.5

I'm getting this error while using compose.io as my server.

**Comment by benfranklin79** [comment]
+1 on 0.8.5

**Comment by lamjo** [comment]
+1

**Comment by danroot** [comment]
+1  mongodb:// support for replica sets such as those provided by compose.io would be nice

**Comment by mirkods** [comment]
+1

**Comment by marcoskoga** [comment]
+1

**Comment by agamanyuk** [comment]
Any updates on the issue?

**Comment by ulpian** [comment]
I don't think it been implemented yet and I can't see any reason why not?

**Comment by lenovouser** [comment]
It might be helpful if you guys would just check the repository + its issues to recognize that this project has been abandoned.

**Comment by agamanyuk** [comment]
@lenovouser I see. I loved robomongo so much. Actually I can't see any good alternative. Ohh

**Comment by ulpian** [comment]
And no-one volunteered to continue maintaining it? Doesn't Robomongo have enough users to collect donations etc?

**Comment by lenovouser** [comment]
Not at the moment, and yes - Robomongo seemed to have more than enough donations. They just abandoned it :disappointed: An alternative is [MongoChef](http://3t.io/mongochef/)

**Comment by zylo47** [comment]
I like how they went ahead and told people to donate for what they wanted us to work on, a bunch of us did (myself included) and now it's abandoned.  Can someone take this project over?  Is it legal for someone to take it over?

**Comment by rfink** [comment]
They took donations and then abandoned the project?  That's really shitty.  This is apparently their website:

https://www.paralect.com/

Might it be worth putting out a warning article on someone's blog or similar?

**Comment by ulpian** [comment]
Well we need to contact the owners and request some answer to this; either return donations or continue maintaining.

**Comment by lenovouser** [comment]
@rfink That is more than shitty. That is disgusting :angry:

**Comment by schetnikovich** [comment]
I'm the original developer of Robomongo. In next two weeks please expect some public announcement from me. It will answer on all your questions, including level of donations that we received and current state of the project. 

Thank you for your patience!

**Comment by agamanyuk** [comment]
@schetnikovich Hope I'll tell us something good:)

**Comment by mtrtm** [comment]
Dmitry,

Hopefully this is good news as I am a huge fan of RoboMongo.

Unfortunately, since there is no support for this issue and now no support
for 3.0, my company has moved and bought licenses for MongoChef.  It's too
bad - I would have been able to take that money (it was a lot, we have
almost 30 licenses) and donate it for things we needed. I hope it's still
an option to use it in the future.

**Comment by ulpian** [comment]
Thank you for making points such as this, it shows that there is a commercial avenue to free-software.

**Comment by mtrtm** [comment]
Yep - agreed.  I love getting my company to support free software.
Fortunately I have a boss that lets me too

**Comment by ulpian** [comment]
I just saw the indiegogo campaign now, it seems without funding this they won't work on any of the issues.

@schetnikovich if funding is not successful what will happen to robomongo project?

**Comment by sleske** [comment]
@ulpian: I don't think they spell this out explicitly anywhere, but my impression was that if funding is not successful, the original authors will not work on Robomongo anymore. At that point it will be an unmaintained free software project. Maybe someone else will step up, maybe not. At least there's a possiblity of someone else doing something - that's the nice thing about free software.

**Comment by ulpian** [comment]
Well said.

I just think the fund raising should have been done earlier if it really was in trouble and they didn't mention anything about the previous donations that were made, would they be returned?

p.s I didn't get why they needed snazzy polished videos of empty dialogue for an open source project funding, why didnt they put that money towards the project??

**Comment by guns2410** [comment]
+1

**Comment by ztmdsbt** [comment]
+1

**Comment by anorsich** [comment]
Latest Robomongo release [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) support connections to the connection to the replica sets (including slaves). @ulpian @ztmdsbt @guns2410 Could you give it a try and let us know if it work for you?

**Comment by anorsich** [comment]
If you'll find any issues, please create a new ticket.

**Comment by moshebeeri** [comment]
I am on RC-4, and can see any thing about connecting to RS.
Any clue will be helpfull

**Comment by anorsich** [comment]
@moshebeeri You should connect to the master or slave of the mongodb as it standalone database. There is nothing special at the moment, but in the future we would love improve that functionality and add support for mongodb [standard connectiong string URI](https://docs.mongodb.org/manual/reference/connection-string/) and also do some sort of replica set members discovery.

**Comment by shlomisas** [comment]
+1 (very missing)

**Comment by mtrtm** [comment]
This thread is 3 years old and I have since moved on.  I would encourage everyone else too as well

**Comment by anorsich** [comment]
@mtrtm @shlomisas We actually do support connections to the replica sets and this ticket was closed few months ago ;) We are still planning to work on some usability features, like master auto discovery and others, but you can give it a shot now.  You can download the latest version can be found [here](https://robomongo.org/download). Robomongo is in active development, hence over 300 commits during last three months. At the moment, we trying to address most critical issues.

Also, in about a week we are going to release support for ssh tunnels and few other things. Stay tuned!

**Comment by shlomisas** [comment]
@anorsich, you're making great work here, really thank you for your efforts..

**Comment by adambuczynski** [comment]
+1 I hope this lands soon..

**Comment by simsekgokhan** [comment]
Hi @adambuczynski and All, we have officially started development for Replica Set Support. Planning to release in next release (0.9.0 RC11). Very sorry for the long delay - Warm Regards from Robomongo Team

**Comment by simsekgokhan** [comment]
Updating milestone. Planned to be included not in the next release (0.9.0 Final) but in the following release 1.0.0.

**Comment by simsekgokhan** [comment]
Hi All, 
We have finally released Robomongo 1.0 RC1 with replica set clusters support, some new features and many improvements. One more time, sorry for long waiting. 

You may see our new blog for an overview:
http://blog.robomongo.org/robomongo-1-rc1/
https://robomongo.org/download
