### ISSUE TITLE
_id field value is incorrectly represented

### ISSUE THREAD

**Issue by dmumladze** [Studio3T/robomongo#1171]
If the "_id" field is integer type, Robomongo treats it as float?

{
    "_id" : 2354315.0,
    "ver" : 67,
    "search" : [ 
        "address", 
        "test"
    ]
}

**Comment by juliashibalko** [comment]
@August2008 thanks for reporting! Could please help us with investigation and if possible share next thing:
* JSON copy of document (`<doc>`) that was inserted before (`db.collection.insert({<doc>})`).   

I'm assuming that document in your example is the result of `db.collection.find()`. Thanks in advance!

**Comment by August2008** [comment]
Yes, it is from db.collection.find({}) but I didn't insert it via Robomongo. Documents have integer value without decimals. MongoDB native shell shows it without decimal.

**Comment by juliashibalko** [comment]
@August2008 thank you for details! I considered situation you've described and seems that things are next.   
**1)**  [MongoDB `shell` treats all numbers as floating-point values by default.](https://docs.mongodb.com/manual/core/shell-types/#numberlong) (please check [question from stackoverflow](http://stackoverflow.com/questions/17185220/mongodb-differences-between-numberlong-and-simple-integer) for details). So it's mean that result of inserting in mongo `shell` will be next:

`> db.myCollectino.insert({num1: 100})`
`> db.myCollection.find({})`
`{"_id" : ObjectId(""), "num1" : 100}`  //despite of number is without '.', it's Double. 

And for Robomongo it will be: 

![image](https://cloud.githubusercontent.com/assets/16773195/18049580/d620c934-6df1-11e6-8e84-f77f890a0357.png)

**2)** MongoDB `shell` has next wrappers to insert integers: [`NumberInt()`](https://docs.mongodb.com/manual/core/shell-types/#numberint) (32-bit Int) and [`NumberLong()`](https://docs.mongodb.com/manual/core/shell-types/#numberlong) (64-bit Int).    

`> db.myCollectino.insert({num1: NumberInt ("101")})`
`> db.myCollection.insert ({num1: numberLong ("102")})`
`> db.myCollection.find({})`
`{"_id" : ObjectId(""), "num1" : 101}`  //now it's integer 32-bit
`{"_id" : ObjectId(""), "num1" : NumberLong(102) }`  //integer 64-bit

Robomongo view: 

![image](https://cloud.githubusercontent.com/assets/16773195/18051580/2692fa52-6dfe-11e6-96c0-f30f3da06021.png)


**3)** To check that's all correct, you could search documents using [`$type` operator](https://docs.mongodb.com/manual/reference/operator/query/type/#type) with `1` (double) value.

`> db.myCollection.find({num1: {$type: 1}})`
`{ "_id" : ObjectId(""), "num1" : 100 } `//only first document

For `_id` field it works in the same way but with one remark: `_id` field is not editable. To update `_id` using mongo `shell` document should be removed first and re-created with new `_id`. In Robomongo this new document will be created automatically without removing old one.

Hope I answered you, please let me know in case of any questions.

**Comment by August2008** [comment]
It should not have .0 at the end. Mongo shell does not have it as well. It is confusing and unnecessary.

**Comment by juliashibalko** [comment]
@August2008 yes, seems that's a good idea not to show ".0" if there is no number after point. We will include into our to-do list and get back to you with updates. Thanks!

**Comment by schetnikovich** [comment]
@August2008, it seems that you have documents with `_id` field of type `Double`, not `Integer`. If you really have integer field with `.0` postfix, then this is a very critical bug of Robomongo. Still I believe that type of `_id` is double. Please check this with the following query:

```
db.yourCollection.find({_id: {$type: 1}})
```

If it finds even single document, it means that there are documents with floating point `_id`. Type `1` means `64-bit binary floating point` in [BSON specification](http://bsonspec.org/spec.html).

Robomongo shows floating point numbers with `.0` postfix in UI, in order to distinguish from 32-bit and 64-bit integers. 

> It should not have .0 at the end. Mongo shell does not have it as well. It is confusing and unnecessary.

It is confusing if you would like to hide the fact that `_id` is floating point number :) You will not see ".0" at the end for integers.

Let me know if you have any questions!
