### ISSUE TITLE
Terminal: "libpng warning: iCCP: known incorrect sRGB profile" warning occurs after launching Robomongo

### ISSUE THREAD

**Issue by gncs** [Studio3T/robomongo#1195]
When expanding "Collections" for the first time I get the following warning:
`libpng warning: iCCP: known incorrect sRGB profile`.
Robomongo 0.9.0-RC10, CentOS 7, libpng 1.5.13.

**Comment by juliashibalko** [comment]
@gncs thank you for reporting! We reproduced this issue and will consider problem fixing in further releases.
