### ISSUE TITLE
Remove manual JSON validation

### ISSUE THREAD

**Issue by revolter** [Studio3T/robomongo#1224]
In the document edit popup, the `Validate` button should be removed, and the validation should be done when trying to save, and:
1. if it's valid:
   - save the document
2. if it's not valid:
   - present to the user an alert saying that the JSON is not valid
   - don't save the document

as there is no case in which someone would want to save a non-valid JSON.

This would have these pros:
1. simpler interface
2. less superfluous
3. safety automatic validation on every save

This could have these cons:
1. could take a lot of time for big documents

**Comment by IlyaDiallo** [comment]
> could take a lot of time for big documents

I don't think that's an issue.
But I think it can also be useful to be able to validate a json without saving it, so auto checking before saving does not imply that the Validate button becomes superfluous.

**Comment by revolter** [comment]
I understand. I personally didn't have the need of validation except when saving, but it makes sense.

**Comment by simsekgokhan** [comment]
I will also agree with @IlyaDiallo, with validate button, users even can use edit dialog as a JSON validator like a validator tool.

**Comment by revolter** [comment]
What about the auto validation on save? Or, what happens if you save an invalid JSON?

**Comment by simsekgokhan** [comment]
Currently, it automatically validates on save, so you should not be able to save invalid JSON.

**Comment by revolter** [comment]
Oh, so it already does this, I didn't know, and was afraid to test it myself. I wonder if other people hit validate before every save. If yes, maybe the button text could be "Validate & Save". If not, this issue can be closed.

**Comment by simsekgokhan** [comment]
Yes, the button text in theory should be "Validate & Save" but in practice it creates text redundancy and does not look nice. Still I think it is a good idea to show what the button does exactly, thanks for the suggestion, we will think about it.

**Comment by revolter** [comment]
Yeah, I thought about the fact that it would look rather ugly, but I can't think of a proper solution either. I'll come back if I think of any.

**Comment by ehiggs** [comment]
I use validate all the time. The behaviour of course will validate either on the client side or the server because the document will need to be valid if the db is going to accept it. I think this can be closed.
