### ISSUE TITLE
“Robomongo” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by itoonx** [Studio3T/robomongo#1301]
I have an issues When i open the Robomongo via MacOS is show me like below 
“Robomongo” can’t be opened because it is from an unidentified developer.

MacOS Sierra

**Comment by simsekgokhan** [comment]
Hi @itoonx , thanks for reporting the problem.

As a temporary workaround, you should be able to open it by right-clicking it
then clicking "open". This will give you the same warning about it being
from an unidentified developer, but will give you the option to proceed
anyway.

Or

Other option is, go to System Preference -> Security & Privacy
Allows apps downloaded from:
Anywhere

Please let us know if it worked.

**Comment by itoonx** [comment]
i am very pleased to tell you, it work great ! 
thank you so much

**Comment by simsekgokhan** [comment]
Glad to hear that. I will close this ticket now. Feel free to open for any reason.
Best Regards.

**Comment by jinsonkv** [comment]
The warning is due to Appl's Gatekeeper Feature.
Check this. to solve the issue.
[https://techiestechguide.com/app-cant-be-opened-because-it-is-from-an-unidentified-developer/](https://techiestechguide.com/app-cant-be-opened-because-it-is-from-an-unidentified-developer/)
