### ISSUE TITLE
Unable to connect to SSH server at IP

### ISSUE THREAD

**Issue by Johngtrs** [Studio3T/robomongo#1305]
I'm on Windows 10 and my server running on Ubuntu 16.04 with Mongodb 3.4.2. I have robomongo 1.0.

I'm trying to connect to my server via ssh but when I click on the `test` button this will take 3 minutes and I got this error : 

```
Failed to create SSH tunnel to ip:22.

Error:
Error when starting up SSH session: -8
```
I tried with another server and it works. But with this server I can't establish a connection via ssh.

Is there something to configure on my server ? I tried to edit /etc/mongod.conf and set the parameter bindIp to `0.0.0.0` or comment bindIp but I have the same problem.

**Comment by simsekgokhan** [comment]
Hi @Johngtrs , thanks for reporting the problem.

Currently, Robomongo does not have official support for MongoDB 3.4. 
3.4 support is planned as top priority task not in the next but in the following release.
For related updates, you can follow us on twitter: https://twitter.com/Robomongo
 or this ticket: https://github.com/Studio3T/robomongo/issues/1250

Can you confirm by trying to connect to MongoDB 3.2 on the same server to be sure that 3.4 is the real problem?

**Comment by Johngtrs** [comment]
Oh okay. My other server running on MongoDB 3.2 and it works. But I don't know how can I downgrade safe and keep my data in the database. So I can't test on this server.

**Comment by simsekgokhan** [comment]
Glad to hear it works with 3.2.

Here is the link how to do it: [How to downgrade-replica-set 3.4](http://docs.mongoing.com/manual-zh/release-notes/3.4-downgrade-replica-set.html#downgrade-3-4-replica-set-to-3-2)

I will close this issue now, feel free to open for any reason.

**Comment by simsekgokhan** [comment]
Hi @Johngtrs , please see [Robomongo 1.1 - Beta version with MongoDB 3.4 Support](https://github.com/Studio3T/robomongo/issues/1250#issuecomment-301036770)
