### ISSUE TITLE
Type Vietnamese in shell

### ISSUE THREAD

**Issue by HaiUIT** [Studio3T/robomongo#1311]
How can I type Vietnamese in Robomogo's shell? My current temporary solution is copy query form a text editor, but It make me lost autocomplete feature.

**Comment by simsekgokhan** [comment]
Hi @HaiUIT , can you share your OS version please?

**Comment by HaiUIT** [comment]
I am using win 10 pro version 1607 build 14393.953 and Robomongo 1.0.0-RC-1

**Comment by simsekgokhan** [comment]
Hi @HaiUIT , I have tested with Windows 10 and Robomongo 1.0.0-RC-1. It worked fine for me. 
I was able to write in Vietnamese as seen below:

<img src="https://cloud.githubusercontent.com/assets/19390749/24599876/e0714620-185a-11e7-8733-a002db86805c.jpg" width="550" />    

1. Can you confirm that you can write Vietnamese on different apps (i.e. notepad) ?
2. Can you confirm Vietnamese is selected as below?
<img src="https://cloud.githubusercontent.com/assets/19390749/24600000/6c065cca-185b-11e7-8186-c8e71e4b9074.jpg" width="250" />    

As a suggestion, after you change the language on Windows settings, try closing and re-opening Robomongo.

**Comment by HaiUIT** [comment]
I think I know the problem. For me and most Vietnamese, we have used [unikey](http://www.unikey.org/) (there are many similar tools, but unikey are the best) + US keyboard layout for typing Vietnamese since we knew about Windows, this tool has not been maintained since 2014, it maybe not work well on some apps in windows 10. But this is the first time I have this problem (maybe I will meet more in future), on my laptop, unikey work well with other "normal" apps (I have not used any metro apps 😄  )
Most of users avoid to use built in keyboard layout for typing Vietnamese because of some reason : 
+ They used to VNI or TELEX input method + US layout for typing Vietnamese.
+ The layout MS introduce increase the typing speed a lot (for details, you can check [this](https://www.quora.com/How-do-Vietnamese-people-type-Vietnamese-letters) and [this](https://answers.microsoft.com/en-us/insider/forum/insider_apps-insider_other/please-support-telex-input-method-for-vietnamese/99df3650-3b17-4eb6-b362-9343d0d6f0d0))

On windows phone, MS support both TELEX and VNI input, i don't know why they not do it for Win 10 😕

**Comment by trunganhDuong** [comment]
Have you solved the problem yet? I'm looking for the solution

**Comment by trunganhDuong** [comment]
Turn off unikey's Vietnamese mode and use OS's built-in Vietnamese mode. It works for me 😄

**Comment by HaiUIT** [comment]
It's the most viable solution at the moment. However it make typing like a nightmare as I said before. So I choose my old temporary  solution :  copy query form a text editor, and try some other tools like unikey.

**Comment by HaiUIT** [comment]
@simsekgokhan 
Yes, at least for programming typing, where numbers and special symbols are used more often than normal typing. In [MS layout for Vietnamese](https://www.microsoft.com/resources/msdn/goglobal/keyboards/kbdvntc.html) , you must use Right Alt for numbers, and Right Alt + Shift for symbols which increase typing time a lot because code files contains large amount of these characters. 

Many tickets from users have been sent to MS since years ago to require them bring the VNI and TELEX (which unikey and other tools provide) built in layout from windows phone to desktop but no luck.

I understand that adding support for unknown 3rd-party tools is quite costly and unneccessary if these tools are not highly require . So, I maybe wait for future update from MS, and continue using my old solution (from a dual-screen machine,, copy Vietnamese part to queries is much faster than typing all of them with bultin layout).

Anyway, thank you very much for your replies.

**Comment by simsekgokhan** [comment]
@HaiUIT 
Thanks a lot to you also for providing details. I also hope Windows will provide better solution for Vietnamese. I will close this ticket now, feel free the open for any reason.

**Comment by trunganhDuong** [comment]
😄  IDK why but there's nothing different with typing using unikey. Copying from a text editor absolutely takes more time than directly typing into robomongo shell

**Comment by HaiUIT** [comment]
@trunganhDuong It is true in a single screen machine, but not for dual screens, one for text editor, one for robomongo shell 😄
