### ISSUE TITLE
download 1.0.0 RC1 broken

### ISSUE THREAD

**Issue by jlwin** [Studio3T/robomongo#1313]
Whenever I try to download the latest version of RoboMongo from https://download.robomongo.org/1.0.0-rc1/windows/robomongo-1.0.0-rc1-windows-x86_64-496f5c2.exe I face a 504 server timeout.
Is this only on my end or a general problem?
Thanks a lot in advance, cheers, JL

**Comment by anorsich** [comment]
@jlwin downloads server is currently down, we are working to get it back. Give it a try in a few hours. We are very sorry for the inconvenience. cc @juliashibalko @gsimsek

**Comment by anorsich** [comment]
You can temporary use this link to download: 
[robomongo-1.0.0-rc1-windows-x86_64-496f5c2.exe.zip](https://github.com/Studio3T/robomongo/files/872222/robomongo-1.0.0-rc1-windows-x86_64-496f5c2.exe.zip)

**Comment by jlwin** [comment]
@anorsich Thanks for the download Andrew & no problem, I was just wondering! Happy to hear that this was already known an you guys are working on it. Thanks a lot, cheers! :-)

**Comment by anorsich** [comment]
@jlwin You are welcome! Downloads now working again, so I think we can close the issue cc @juliashibalko

**Comment by juliashibalko** [comment]
@anorsich thanks a lot!
Closing as fixed.
