### ISSUE TITLE
Robomongo 1.0 RC1 doesn't support Chinese input in the command shell

### ISSUE THREAD

**Issue by yyblove** [Studio3T/robomongo#1321]
I use the linux release, in Ubuntu16.04

**Comment by simsekgokhan** [comment]
Hi @yyblove , thanks for reporting the problem.
Are you using Ubuntu system builtin keyboard or any external tool (non-system) for Chinese keyboard? 

We have similar issue with Vietnamese, it works with system keyboard but it does not when external tool (i.e. Unikey) is used. You can see more details here: https://github.com/Studio3T/robomongo/issues/1311#issuecomment-292239324

**Comment by juliashibalko** [comment]
Hi @yyblove! Could you please check issue with Robo3T 1.1 if possible? Also please check comment above and if possible share with us your keyboard settings. Thanks in advance!
Please see new release here https://robomongo.org/download.

**Comment by yyblove** [comment]
I copy dir `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/` to Robomongo dir `lib`, and restart Robomongo
