### ISSUE TITLE
Error when connecting to mongodb atlas

### ISSUE THREAD

**Issue by tomganguz** [Studio3T/robomongo#1325]
When connecting to mongodb atlas with ssl on self signed mode, appear an error that say "SSL connection failure:No SNI name sent, make sure using a MongoDB 3.4+ driver/shell".

here an image:
![issue](https://cloud.githubusercontent.com/assets/11964961/25184431/afaa6770-251a-11e7-9a07-688919d2fb1a.PNG)
Currently I use the latest version of robomongo
Thank you for all!

**Comment by simsekgokhan** [comment]
Hi @tomganguz , thanks for reporting the problem. Currently, Robomongo does not support MongoDB 3.4, and we are at development stage of MongoDB 3.4 support so this error is expected.

For news about 3.4 support, you can follow us twitter https://twitter.com/Robomongo and/or follow this ticket: https://github.com/paralect/robomongo/issues/1250

It is the highest priority task right now, we are looking forward to make 3.4 support available in 3-4 weeks.

I will close this issue. Feel free to re-open for any reason.

**Comment by simsekgokhan** [comment]
@tomganguz 
Please see the beta: [Robomongo 1.1 - Beta version with MongoDB 3.4 Support](https://github.com/Studio3T/robomongo/issues/1250#issuecomment-301036770)
