### ISSUE TITLE
Roboto renames DNS names and breaks connection

### ISSUE THREAD

**Issue by xuvez** [Studio3T/robomongo#1336]
Robomongo changes (renames) my connection and doesn't allow me to connect.

`[thread3] changing hosts to my-rs/mongo-replica-node-0:27017,mongo-replica-node-1:27017,mongo-replica-node-2:27017 from my-rs/mongo-replica-node-0.xxxx.svc.cluster.local:27017,mongo-replica-node-1.xxxx.svc.cluster.local:27017,mongo-replica-node-2.xxxx.svc.cluster.local:27017`

This happens because my DNS are able to resolve `mongo-replica-node-0.xxxx.svc.cluster.local` but I don't have any "search" at my `resolv.conf`. So the only way for me for connecting is change the connection endpoints to `mongo-replica-node-0,....` and add it to my `/etc/hosts` file

**Comment by simsekgokhan** [comment]
Hi @andresju , thanks for reporting the problem.
First of all, some technical details, those logs you are seeing are coming from MongoDB code which Robomongo is using (not directly from Robomongo code), and they are not error logs just informational. 

I just did some testing on windows with Mongo Atlas. Seems like, it only enters that part of the code when I **_do not_** enter all of the replica members on Robomongo. So solution for me to enter all the members of replica set correctly on Robomongo.

So please make sure you enter the replica member names correctly on Robomongo (and maybe set name as well as second step). Check the correct member names from the output of this command `rs.status()` on server.

Please let us know how it went.

**Comment by juliashibalko** [comment]
Hi @xuvez! Could you please check issue with Robo3T 1.1 if possible? Also please check comment above and share with us of solution worked.
Please see new release here https://robomongo.org/download.
