### ISSUE TITLE
Robomongo fails to create user for database

### ISSUE THREAD

**Issue by voplex95** [Studio3T/robomongo#1338]
Mongo DB: v3.4.4 (installed via brew, localhost)
Robomongo: v1.0.0
OS: macOS Sierra 10.12.2

Hi, got a problem.
Can not create user for database (both **admin** and **custom one**). While Robomongo displays "created" user in Users section of my database, it does not exist (_db.getUsers()_ returns an empty array). Of course, I can try creating user via mongo shell, but since you provide such a functionality, it should work.

Cheers

**Comment by voplex95** [comment]
Ok, my bad... Didn't noticed that...

> Currently in progress:
> MongoDB 3.4 Support

**Comment by simsekgokhan** [comment]
Hi @voplex95 , thanks for reporting the problem, user management on Robomongo UI has known issues and must/will be re-implemented soon. I strongly suggest to use Robomongo shell for user related ops for now.

For 3.4 support you can follow this ticket: https://github.com/Studio3T/robomongo/issues/1250 or Robomongo twitter.

**Comment by simsekgokhan** [comment]
@voplex95 
Please see the beta: [Robomongo 1.1 - Beta version with MongoDB 3.4 Support](https://github.com/Studio3T/robomongo/issues/1250#issuecomment-301036770)
And from my previous comment, please use Robomongo shell for user related ops for now.
