### ISSUE TITLE
Results not propperly displayed

### ISSUE THREAD

**Issue by lkappeler** [Studio3T/robomongo#1341]
When performing multiple queries in the same shell the results are overflowing my display and I am not able to see them. I would expect the window to become scrollable when it displays more stuff than I have space fore on my screen

![screen shot 2017-05-05 at 15 48 01](https://cloud.githubusercontent.com/assets/3371760/25748227/b64962ba-31aa-11e7-850f-c1d25b49a738.png)

(Bottom of the screen shot = bottom of my screen)

OS: OSX 10.11.6 
Robomongo: 1.0.0

**Comment by juliashibalko** [comment]
Hi @lkappeler , thank you a lot for reporting! It's known issue and we are very sorry for that.
But let me suggest you to track progress with #10 ticket (seems that issues are the same). We will get back to you with any news.
I'm closing this one as duplicate, but feel free to reopen it in any case. Thank you!
