### ISSUE TITLE
crtl+enter stopped working after we search some specific keyword

### ISSUE THREAD

**Issue by prashantp995** [Studio3T/robomongo#1360]
![image](https://cloud.githubusercontent.com/assets/17299110/26444631/d1b358c0-415a-11e7-9999-e915867fea06.png)
steps to replicate :
1)  open shell
2) press ctrl+f and type sonmething to search 
3)  move your mouse cursor to query area again . 
4) press crtl+enter

**Comment by juliashibalko** [comment]
Hi @prashantp995, thanks a lot for reporting! I managed to reproduce it, so we will consider to fix it in further releases.
As small workaround, if you press ESC button, 'Search' box will close and ctrl+enter will work again.

**Comment by prashantp995** [comment]
That was Quick!! ..  Please let me know the fix too .. would love to explore more on robomongo code base.

**Comment by simsekgokhan** [comment]
@prashantp995  Feel free to re-open if you still have the problem with latest version. We are unable to reproduce.
