### ISSUE TITLE
Getting error "can’t be opened because it is from an unidentified developer"

### ISSUE THREAD

**Issue by meganmcd** [Studio3T/robomongo#1362]
Tried to install robomongo.org from Mac OS Sierra. But not able to use because of error "can’t be opened because it is from an unidentified developer" 

Can you please look into the issue

Regards,
Megan

**Comment by juliashibalko** [comment]
Hi @meganmcd, thanks for reporting!
It's known issue and it's in our wait-list. To launch Robomongo, you might be able to open it by right-clicking it then clicking "open". This will give you the same warning about it being from an unidentified developer, but will give you the option to proceed anyway (check https://github.com/Studio3T/robomongo/issues/963#issuecomment-153423289).
I'll close this issue as duplicate. But feel free to reopen it or simply add comment to opened https://github.com/Studio3T/robomongo/issues/963

**Comment by nalsuresh** [comment]
Hello, tried installing Robocode on my MAC. I got this error. What is this error telling?
“robocode-1.9.3.6-setup (1).jar” can’t be opened because it is from an unidentified developer.
