### ISSUE TITLE
Unable to connect to MongoDB on mlab.com

### ISSUE THREAD

**Issue by mandazi** [Studio3T/robomongo#1363]
I am sure the authentication user, password, host, port are all correct. I've checked several times and I use it in my Node.js application and it works there.  I have tried to uninstall and install RoboMongo and it still doesn't work.  I am not sure what I am doing wrong.

**Comment by mandazi** [comment]
![image](https://cloud.githubusercontent.com/assets/340385/26588302/f15dfb00-4522-11e7-89bd-f21525b587ee.png)


This is the message I keep getting.

**Comment by juliashibalko** [comment]
Hi @mandazi, could you please share error message occurring on connection, robomongo version and OS version?
Also let me suggest to check next three comments with possible workaround solutions:
1.  Just to re-check that everythin is correct using provided screenshots: https://github.com/Studio3T/robomongo/issues/949#issuecomment-237190894
2. Re-check database and Auth type: https://github.com/Studio3T/robomongo/issues/949#issuecomment-255523387
3. One more solution: https://github.com/Studio3T/robomongo/issues/949#issuecomment-254076148

**Comment by mandazi** [comment]
Error message
![image](https://cloud.githubusercontent.com/assets/340385/26595147/6908f712-4538-11e7-9ba6-04cecfcce049.png)

**Comment by mandazi** [comment]
I tried all those 3 solutions and it still hasn't worked.  I am using the user for that specific mongo db instance.  I am also using SCRAM-SHA1 as the auth mechanism.

**Comment by mandazi** [comment]
I am on Windows 10, RoboMongo 1.0.0

**Comment by mandazi** [comment]
Oh wow. I got it to work! Thank you!  I uninstalled and reinstalled RoboMongo.
