### ISSUE TITLE
count() method doesn't show result

### ISSUE THREAD

**Issue by Marimout** [Studio3T/robomongo#1366]
Since Robomongo 1.0.0, the count() method doesn't show result anymore. I remember that I was still able to execute the same command in RC version few days before. 

Command execute : 
`        db.collection-name.count()`
or 
`        db.getCollection('collection-name').count()`

What is shown in result panel : 
`        Script executed succesfully, but there are no results to show.`

Can you please have a look ? 

Thanks.

**Comment by juliashibalko** [comment]
Hi @Marimout, thanks for reporting!
We didn't manage to reproduce the issue, but I can guess and suggest you to increase `shellTimeoutSec` value in `.config` file (especially if there is a big amount of documents in collections). Pleas check next comment here https://github.com/Studio3T/robomongo/issues/1106#issuecomment-230258348.
Please let us know if it works for you.

**Comment by Marimout** [comment]
Thanks for your answer. It seems that it was a temporary issue with my Robomongo. After restarting the machine (and Robomongo, of course), the count() works again.

Sorry for disturbing.
