### ISSUE TITLE
Fonts on a Mac OS X still no workie

### ISSUE THREAD

**Issue by ccpalmer** [Studio3T/robomongo#1367]
No matter where I put the following lines:

```javascript
{
 "textFontFamily" : "Andale Mono",
 "textFontPointSize" : 24
}
```
in these directories:
```bash
/Users/ccpalmer/.config/robomongo/
├── 0.9
│   └── robomongo.json
├── 1.0.0
│   └── robomongo.json
├── 1.1
│   └── robomongo.json
└── 1.1.0
    └── robomongo.json

4 directories, 4 files
```
again in ~/.3T/robomongo just in case,  and even in
```bash
~/.mongorc.js
```
with the "Load .mongorc.js" option checked,  the appearance of Robomongo1.1 does not change.  I've tried several different fonts and sizes.

I know this has been discussed here, but the Linux answers don't apply and the others describe what I did above.  Surely I missed something ... or perhaps this is just "in the queue for consideration."

Charles

**Comment by simsekgokhan** [comment]
Hi @ccpalmer, thanks for reporting the problem.

No need to create any files, you should be modifying existing file:
`    /Users/<user>/.3T/robomongo/1.1.0/robomongo.json`

(You can also see/verify your config file location on 'Logs' window right bottom corner of Robomongo main window)

More: [Robomongo-Config-File-Guide](https://github.com/Studio3T/robomongo/wiki/Robomongo-Config-File-Guide)

There are other ways to increase the font size.
But first, can you attach a screenshot of the problem and share your exact OS versions?

**Comment by ccpalmer** [comment]
Woohoo!  That was it!  I looked at the log and found the directory was 

`/Users/<userid>/.3T/robomongo/1.1.0-Beta/robomongo.json`

I edited the json file there and ALL IS FIXED!

Yay RoboMongo!  My students appreciate you!
ccp

**Comment by simsekgokhan** [comment]
@ccpalmer 
Very happy to hear that :) Thanks for the feedback.
