### ISSUE TITLE
Robomongo 0.9.0 rc9 crashed

### ISSUE THREAD

**Issue by DeepzSandra** [Studio3T/robomongo#1371]
Robomongo  crashing every time.how can i solve this problem.

OS version : windows 7 (for system test)
mongodb version : 3.2.7 version
Robomongo version: 0.9.0 rc9

**Comment by simsekgokhan** [comment]
Hi @DeepzSandra , thanks for the details.

Does Robomongo crash on start just after clicking? If not please share steps (or condition) to reproduce the crash. We are unable to reproduce this crash.

Can you also share the crash logs (dump file) please?

The dump file (*.mdmp) is the file required for investigation. It is generally produced after a crash on windows machines.

**Example:**

<img src="https://cloud.githubusercontent.com/assets/19390749/22237063/70575328-e21a-11e6-92c8-fe676308f15d.jpg" width="400" />

**Comment by juliashibalko** [comment]
Hi @DeepzSandra, could you please check latest version of Robo3T 1.1 (https://robomongo.org/download) and share results with us?
