### ISSUE TITLE
SSH timeout in Robomongo 1.0.0

### ISSUE THREAD

**Issue by Bersam** [Studio3T/robomongo#1377]
7:13:04 PM	Info: Creating SSH tunnel to SSH_IP:SSH_PORT...
7:15:05 PM	Error: Resource temporarily unavailable. Error when starting up SSH session: -8
. (Error #11)

I'm connecting successfully with same information on terminal without any problem. and it was working on Robomongo Rc 0.9.

**Comment by simsekgokhan** [comment]
Hi @Bersam , thanks a lot for reporting this problem.
This is a known issue unfortunately we cannot reproduce and we still investigate.
Please see the related ticket, there are some solutions but not working for everyone:
https://github.com/Studio3T/robomongo/issues/1125

**Comment by simsekgokhan** [comment]
Hi @Bersam , can you reproduce the problem with latest version [Robo 3t 1.1](https://robomongo.org/download) ?
We have updated openssl version, it might change the result.

**Comment by Bersam** [comment]
@simsekgokhan @juliashibalko It's fixed in Robo 3t 1.1, sorry for late response.
