### ISSUE TITLE
Creating, Viewing and Authenticating users

### ISSUE THREAD

**Issue by tjoe4u** [Studio3T/robomongo#1378]
When a new user is created using Robomongo, it saves the `_id` as `ObjectId`, but when you create a user using the `mongo` shell, it saves the `_id` as the `<name of the collection>.<username>`.
Robomongo cannot read users created on `mongo` shell. When you click on `Users` for a collection it shows this error:
![image](https://user-images.githubusercontent.com/5625068/27007062-6ba6e8ae-4e3d-11e7-8190-2be2cac0d987.png)

`Users` created using Robomongo cannot be authenticated.

**Comment by juliashibalko** [comment]
Hi @tjoe4u, thank you a lot for reporting! It's known issue and we are very sorry for that.
But let me suggest you to track progress with https://github.com/Studio3T/robomongo/issues/1041 and https://github.com/Studio3T/robomongo/issues/638 tickets (seems that issues are the same). We will get back to you with any news.
I'm closing this one as duplicate, but feel free to reopen it in any case. Thank you!
