### ISSUE TITLE
Windows 64bit Portable package missing libeay32.dll

### ISSUE THREAD

**Issue by purveshpatel** [Studio3T/robomongo#1379]
I downloaded the 64bit Portable zip package of Robomongo 1.0 and on startup it gave error message of missing LIBEAY32.dll

But 64bit executable package is having this LIBEAY32.dll. I copied this to portable package and it started.
![missing_libeay](https://user-images.githubusercontent.com/13252956/27013148-0493e1d4-4efc-11e7-9fe2-df1209fedf4d.JPG)

**Comment by simsekgokhan** [comment]
Hi @purveshpatel , No other user reported this problem, and I double checked the portable installer from robomongo.org. I see LIBEAY32.dll inside installer. Did you download the installer from robomongo.org?

**Comment by purveshpatel** [comment]
Yes I downloaded it from robomongo.org only. Its strange I downloaded it today and the file is there.
