### ISSUE TITLE
Robomongo 1.0.0 - 'find' with regex is case sensitive

### ISSUE THREAD

**Issue by guttentag** [Studio3T/robomongo#1380]
When using a 'find' query, the search is case sensitive.
for example:
db.collection('users').find({"name": /jake/}) will return 0 results even if users named 'Jake' exists

**Comment by juliashibalko** [comment]
Hi @guttentag, thanks for reporting issue!
Regex is case-sensitive by default. To make it insensitive, simply add `i` flag at the end of expression:
`db.collection('users').find({"name": /jake/i}) `
Please refer to mongoDB docs https://docs.mongodb.com/manual/reference/operator/query/regex/#op._S_options.
I'm closing this issue, but please feel free to reopen in any case.

**Comment by guttentag** [comment]
Thanks for the response.
actually this is also on 'regular' query. is there a way to `db.collection('users').find({"name": "jake"})` to apply for 'jake' and 'Jake'?

**Comment by juliashibalko** [comment]
@guttentag as Robomongo embeds the actual mongo shell, you can simply check MongoDB documentation. At first sight here can be an answer https://docs.mongodb.com/manual/reference/command/find/ but I'm not really sure of it. Maybe new feature in mongoDB 3.4 `collation` will help somehow.

**Comment by guttentag** [comment]
Thanks
