### ISSUE TITLE
bash: ./robo3t: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by krazylearner** [Studio3T/robomongo#1381]
Hi

Steps i followed
1.downloaded the robomongo client from this link 
https://download.robomongo.org/1.1.1/linux/robo3t-1.1.1-linux-x86_64-c93c6b0.tar.gz
2. $ tar -xvf  robo3t-1.1.1-linux-x86_64-c93c6b0.tar.gz
3. $ cd extracted _directory/bin
4 $./robo3t

Also when i go directly inside bin folder and double click robo3t file it creates a new file named @8(invalid encoding)

**System specification**

```
govind@govind-desktop:~/robo3t-1.1.1-linux-x86_64-c93c6b0/bin$ arch
i686
govind@govind-desktop:~/robo3t-1.1.1-linux-x86_64-c93c6b0/bin$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```
Please help
Thanks

**Comment by simsekgokhan** [comment]
Hi @krazylearner , thanks for reporting the problem. 
Any chance you have 32-bit OS? If so, that might be the problem. You will need 64-bit to run Robomongo. 
Can you make sure if you are running on 64-bit by running `uname -i` or from desktop "Settings->About This Computer" ?
```
// Example output for 64 bit 
# uname -i
x84_64
```

**Comment by krazylearner** [comment]
yes the system is 32 bit .

does this mean robomongo only works on 64 bit system ?

thanks

**Comment by simsekgokhan** [comment]
@krazylearner Yes
