### ISSUE TITLE
Robo 3T "unidentified developer" message on MacOS

### ISSUE THREAD

**Issue by yonatang** [Studio3T/robomongo#1386]
Trying to open the latest 1.1 version in MacOS Sierra results in:

> **“Robo 3T.app” can’t be opened because it is from an unidentified developer.** 
Your security preferences allow installation of only apps from the App Store and identified developers.

Although it is easily solvable, the registered developer of the app should have the required certificates to avoid such message. Especially after 3T has acquired the application formerly known as RoboMongo.

**Comment by juliashibalko** [comment]
Hi @yonatang, thanks for reporting!
It's known issue and we are very sorry for that! It's in our wait-list. But let me suggest you to check progress with ticket #963.
I'll close this issue as duplicate. But feel free to reopen it or simply add comment to #963.

**Comment by cubanjlm** [comment]
@yonatang, you can also modify your security settings, allowing Robo 3t to run on your MacOS Sierra.
https://kb.wisc.edu/page.php?id=25443. It worked for me, I hope for you to. Greetings

**Comment by sudeepdk** [comment]
thanks

**Comment by joquijada** [comment]
What worked for me was running this command on my Mac OS machine, replace `Some.app` with the actual app, this solution is suggested in #963,

```
udo xattr -r -d com.apple.quarantine /Applications/Some.app
```

**Comment by swapnilnshelar** [comment]
Thanks your suggestion worked, but looks to be a small type, it should be *sudo*
sudo xattr -r -d com.apple.quarantine /Applications/Some.app

**Comment by joquijada** [comment]
> Thanks your suggestion worked, but looks to be a small type, it should be _sudo_
> `sudo xattr -r -d com.apple.quarantine /Applications/Some.app`

Fixed, thanks, and glad it worked!

**Comment by yohainnn** [comment]
sudo xattr -r -d com.apple.quarantine /Applications/Robo\ 3T.app

thank you all dumbasses above me

**Comment by RajendraMangekar** [comment]
sudo xattr -r -d com.apple.quarantine /Applications/Robo\ 3T.app
Thanks Yohainnn...it worked for me!!!

**Comment by sbaraka** [comment]
@yohainnn thank you for dummies like me

**Comment by jhasidmedrano** [comment]
Thanks your suggestion worked!
But in my case i needed to install robo3t modifying the system preference and then i returned the values default. After all that i run the command line: 

sudo xattr -r -d com.apple.quarantine /Applications/Robo\ 3T.app

**Comment by natashamalam** [comment]
Work around:

Go to System Preferences -> Security and Privacy -> General
Towards the bottom, a message is shown that Robo 3T is blocked. Select Open Anyway.

That should do the work!

**Comment by omril1** [comment]
Is this a reoccurring issue? I just tried to install the latest version and got this error

**Comment by DolevBria** [comment]
Got this error as well.
