### ISSUE TITLE
Can not connect to multiple replica sets with same set name

### ISSUE THREAD

**Issue by lmachens** [Studio3T/robomongo#1388]
I have two replica sets with different members.
Both replica sets names are "rs0".

It is not possible to create a connection two the second added replica set.

![image](https://user-images.githubusercontent.com/10058950/27287450-f5661714-5503-11e7-92a1-f9d44b682b45.png)

What can I do besided renaming the MongoDB replica sets?

Version:
Robo 3T - 1.1
(Offtopic: Error message still speaks about Robomongo).

**Comment by simsekgokhan** [comment]
Hi @lmachens , thanks for reporting the problem. As the error message tries to say, unfortunately, currently connections to same set names are not supported under one program instance. Solution is to open and work on another instance of Robo 3T for each set with the same set name.

**Comment by lmachens** [comment]
Thx! Multiple instances works fine for me.

**Comment by PXMYH** [comment]
Any updates since then? This issue still exists

**Comment by mnevadom** [comment]
how can this not work in one instance!?

**Comment by mnevadom** [comment]
several years with this problem... im going to delete it right now!!
