### ISSUE TITLE
Feature request: Hotlink references

### ISSUE THREAD

**Issue by mtrogers** [Studio3T/robomongo#1389]
A task I found myself doing frequently:
I run a query on a collection. The resulting document(s) have a reference to a document in a different collection via ObjectID. In order to inspect the referenced document, I have to copy the ObjectID, open up a tab to the proper collection, and setup the query to retrieve that document.

It would be particularly time saving if double clicking an ObjectID value would open a new tab with the appropriate query automatically. An onHover inspection of the document would be great, especially if there was a UI option for the previous suggestion.

Thanks for the consideration, I do love this tool.

**Comment by juliashibalko** [comment]
Hi @mtrogers, thanks a lot for reporting and your warm words!
Am I correct assuming that we have this feature already been requested https://github.com/Studio3T/robomongo/issues/377? Let me close this ticket as duplicate and suggest you to track progress within that ticket #377. We will get back to you with any updates! 
Feel free to re-open card in any case.
