### ISSUE TITLE
Network is Unreachable Error

### ISSUE THREAD

**Issue by Imperial7** [Studio3T/robomongo#1390]
I keep Gettings this Error when I try to create a new connection

http://imgur.com/a/S7RAD

I hope you can Help

**Comment by simsekgokhan** [comment]
Hi @Imperial7 , thanks for reporting the problem, can you give more details?
Versions of Robomongo, mongodb, OS etc..

**Comment by pantherso48** [comment]
I am having the same issue:
robomongo: 1.1
mongodb: 3.4.5
OS: Windows 10
mLab: used with Heroku

I have a mongo instance on mLab and cannot connect to it through robomongo, error below:
<img width="338" alt="capture" src="https://user-images.githubusercontent.com/13629866/28386480-b0f49b84-6c99-11e7-806c-f2cd7a94c9a6.PNG">

**Comment by agolia** [comment]
Same issue here. Same versions as @pantherso48.  Is this issue being addressed?

**Comment by JackZhouMine** [comment]
Same issue here.
robomongo: 0.9.0
mongodb: 2.15.1
OS: Windows 7
