### ISSUE TITLE
Robo3t crashes on Ubuntu 16.04 on startup

### ISSUE THREAD

**Issue by chrisspen** [Studio3T/robomongo#1392]
The current binary release for Linux appears to be unusable on Ubuntu 16.04.

    $ tar xvzf robo3t-1.1.1-linux-x86_64-c93c6b0.tar.gz 
    $ cd robo3t-1.1.1-linux-x86_64-c93c6b0/bin
    $ ./robo3t 
    This application failed to start because it could not find or load the Qt platform plugin "xcb"
    in "".

    Available platform plugins are: xcb.

    Reinstalling the application may fix this problem.
    Aborted (core dumped)

Googling the error shows some suggesting I'm missing certain X11 and Qt packages, but installing all the recommended packages does not fix the problem.

**Comment by simsekgokhan** [comment]
Hi @chrisspen , thanks for reporting the problem.
This is a known issue and until now we only received the issue with Ubuntu 17.04. So no Ubuntu 16 or 14 user reported this problem.

I hope the workaround solution here will help you: https://github.com/Studio3T/robomongo/issues/1384#issuecomment-310014541

**Comment by fernandosantucci** [comment]
I have the same XCB problem on Robo3T v1.1 with Ubuntu 16.04 LTS with kernel 4.8, gcc 5.4 and MongoDB 3.4.6.

I unzip the tar to directory /opt and change the owner to root:
```
sudo mv ./robo3t-1.1.1-linux-x86_64-c93c6b0 /opt
cd /opt
sudo chown -R root:root ./robo3t-1.1.1-linux-x86_64-c93c6b0
```
When I run the app I got the XCB error messages:
`./robo3t-1.1.1-linux-x86_64-c93c6b0/bin/robo3t`

Move the libstdc++* dependencies to another directory also not work.

I think not be just rebuild and recompile the project, maybe need review the dependencies for Ubuntu 16.04 LTS release.

I always used Robomongo in LTS releases with no problem, before Studio 3T acquisition.

Please, consider packaging a single Snap for all Linux distros and releases!

**Comment by neriberto** [comment]
The same issue here!

**Comment by kevinjanada** [comment]
Same Issue with me too also on Ubuntu LTS 16.04

**Comment by karthikeyana** [comment]
Kindly follow this procedure its working fine

```
mkdir ~/robo-backup
mv robo3t-1.1.1-linux-x86_64-c93c6b0/lib/libstdc++* ~/robo-backup/
robo3t-1.1.1-linux-x86_64-c93c6b0/bin/robo3t
```

**Comment by kevinjanada** [comment]
Thanks! That worked

**Comment by wajihweriemi** [comment]
is there anyway to fix that the right way ? I realy don't want a "robo-backup" folder in my home directory

**Comment by raeesaa** [comment]
Same issue here. Even I am on Ubuntu LTS 16.04.

**Comment by lu1tr0n** [comment]
Funciona el procedimiento que realizaste. Gracias :+1: / The procedure you performed works. Thanks: +1:

**Comment by luizpericolo** [comment]
@karthikeyana 
The procedure worked. Cheers!

**Comment by obelich** [comment]
i have the same issue :( 

This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
[1]    13675 abort (core dumped)  ./robo3t

**Comment by shobhit-github** [comment]
Thanks @karthikeyana

**Comment by BlueT** [comment]
Same issue on Ubuntu 16.04 64bit

**Comment by snbhalgat** [comment]
Same issue

Thaks @karthikeyana, it worked for me.

**Comment by chipmunkgeek** [comment]
@karthikeyana Worked for me. :+1:

**Comment by rafaelvalero** [comment]
Thank you very much it works for me in Ubuntu 16.04. Best

**Comment by LimaBruno** [comment]
Thanks @karthikeyana!

**Comment by KPontes** [comment]
I did not understand the reason for the robo-backup procedure, but it worked for me on Ubuntu 16.04

Thanks

**Comment by amitmcp100** [comment]
hgfdfgfdgf

**Comment by ngvcanh** [comment]
It not working for me
