### ISSUE TITLE
Robo 3T controls and text is so small

### ISSUE THREAD

**Issue by matgenois** [Studio3T/robomongo#1394]
As you can see on this image, everything is so small, almost unusable. This as begun when I was using Robomongo 0.9. Then I' have upgraded, I have deleted ~/.config/robomongo/* and ~/.3T/* and I have  didn't change anything. Help would be greatly appreciated. I have an Asus US303ub where resolution is like 3600x1800 but i run it in 1800x900 because in default resolution, everything is so small. Don't know if it could be linked.

![image](https://user-images.githubusercontent.com/7738711/27541196-0459316e-5a51-11e7-9d1f-5a919ae74a53.png)

**Comment by simsekgokhan** [comment]
Hi @matgenois , thanks for reporting the problem.
It is a known problem and it is in our priority list.

Can you try the methods below?

**1 )** Increase all UI element size (change QT_SCALE_FACTOR)

a) On the fly
QT_SCALE_FACTOR=1.5 /path/to/robo3t

More: https://github.com/Studio3T/robomongo/issues/1199#issuecomment-295134277

b) Permanently
This option should change all Qt-based system applications icon/text size.
https://github.com/Studio3T/robomongo/issues/1104#issuecomment-244914667

**2 )** Change "textFontPointSize" in config file
This option should change only Robo 3T text font size.
See: https://github.com/Studio3T/robomongo/issues/1231#issuecomment-260683555

**Comment by matgenois** [comment]
I can confirm that 1a and 1b works fine. 1b has generated error report  on reboot so I think i'll use 1a through a script if I get these errors on every boot. Thanks!

**Comment by dandv** [comment]
This is still a problem in the commercial Studio 3T product. Only the editor font can be configured. Query results look very small, and seemingly impossible to zoom into. MongoDB Compass supports zooming.

**Comment by moodboom** [comment]
I found that setting QT_FONT_DPI=128 worked better than other suggestions here. Qt really needs to get their act together!

eg: `QT_FONT_DPI=128 bin/robo3t &`

**Comment by tadhgoc** [comment]
I created an application shortcut using the scale factor, simply copy `/var/lib/snapd/desktop/applications/robo3t-snap_robo3t.desktop` to `~/.local/share/applications` and on the Exec line add `env QT_SCALE_FACTOR=1.5`, or `QT_FONT_DPI=128 ` if you prefer that. I also updated the name line to be Robo3t BIG, that way I can easily access both shortcuts easily - I've also attached my file
[robo3t-snap_robo3t.desktop.txt](https://github.com/Studio3T/robomongo/files/6851879/robo3t-snap_robo3t.desktop.txt)

**Comment by dragnev** [comment]
Where can is the config file located in windows environment?

**Comment by hpichukala** [comment]
Where should we modify these settings in Mac

**Comment by nitzcard** [comment]
I'm joining [hpichukala](https://github.com/hpichukala) request.
Where in mac?
