### ISSUE TITLE
Robo3T 1.1: issue with replica sets (URGENT)

### ISSUE THREAD

**Issue by mssatheesh87** [Studio3T/robomongo#1395]
Hi,
I am new to replicaset .... i am getting error while enabling authentication in mongo config at primary server ..
If authentication enabled primary and secondary node changing to Recovering mode .... If i disabled authentication it works like normal ...

Cannot connect to replica set "proddb1"[xx.xx.xx.33:27017]. 
Set's primary is unreachable.

Reason:
No member of the set is reachable.

Mongo Config: mongod.conf in both primary and secondary

systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

storage:
  dbPath: /var/lib/mongo
  journal:
    enabled: true

  port: 27017
# bindIp: 127.0.0.1
security.authorization: enabled
replication.replSetName: prod

**Comment by simsekgokhan** [comment]
Hi @mssatheesh87 , we will try to help.
Please make sure you enter the set members IP and ports correctly on Robo 3T. It should be same as the output of `rs.status()`.

Can you share your Robo 3T connection settings tabs and the output of `rs.status()`?
Also make sure you can connect to your set or a single node with `mongo` on command line to verify your configuration is correct.

**Comment by mssatheesh87** [comment]
Thanks for your kind reply @simsekgokhan ...

yes i am able to connect with Direct connection to primary and secondary separately... If i select replicaset it fails ....

Mongodb version: 3.4.5.1

ROBOMongo config:

Type: Replicaset
name : newconnection
Members: 
xx.xx.xx.33:27017
xx.xx.xx.34:27017
setname: prod
Auth mechanism : SCRAM-SHA-1

rs status:(primary)

/* 1 */
{
    "set" : "prod",
    "date" : ISODate("2017-06-28T07:12:48.316Z"),
    "myState" : 3,
    "term" : NumberLong(52),
    "heartbeatIntervalMillis" : NumberLong(2000),
    "optimes" : {
        "lastCommittedOpTime" : {
            "ts" : Timestamp(0, 0),
            "t" : NumberLong(-1)
        },
        "appliedOpTime" : {
            "ts" : Timestamp(1498615216, 1),
            "t" : NumberLong(52)
        },
        "durableOpTime" : {
            "ts" : Timestamp(1498615216, 1),
            "t" : NumberLong(52)
        }
    },
    "members" : [ 
        {
            "_id" : 0,
            "name" : "proddb1:27017",
            "health" : 1.0,
            "state" : 3,
            "stateStr" : "RECOVERING",
            "uptime" : 11620,
            "optime" : {
                "ts" : Timestamp(1498615216, 1),
                "t" : NumberLong(52)
            },
            "optimeDate" : ISODate("2017-06-28T02:00:16.000Z"),
            "infoMessage" : "could not find member to sync from",
            "configVersion" : 2,
            "self" : true
        }, 
        {
            "_id" : 1,
            "name" : "proddb2:27017",
            "health" : 0.0,
            "state" : 6,
            "stateStr" : "(not reachable/healthy)",
            "uptime" : 0,
            "optime" : {
                "ts" : Timestamp(0, 0),
                "t" : NumberLong(-1)
            },
            "optimeDurable" : {
                "ts" : Timestamp(0, 0),
                "t" : NumberLong(-1)
            },
            "optimeDate" : ISODate("1970-01-01T00:00:00.000Z"),
            "optimeDurableDate" : ISODate("1970-01-01T00:00:00.000Z"),
            "lastHeartbeat" : ISODate("2017-06-28T07:12:45.556Z"),
            "lastHeartbeatRecv" : ISODate("1970-01-01T00:00:00.000Z"),
            "pingMs" : NumberLong(0),
            "authenticated" : false,
            "configVersion" : -1
        }
    ],
    "ok" : 1.0
}

If i comment security.authorization: enabled in mongod.conf and restart service means everything works normal as primary ,secondary 

Kindly advise on this ...

**Comment by simsekgokhan** [comment]
Seems to me there is a problem on replica set config/setup.
Because both of your nodes are not in good state.
```
"name" : "proddb1:27017",
"stateStr" : "RECOVERING",
...
"name" : "proddb2:27017",
"stateStr" : "(not reachable/healthy)",
```

Example of a healthy replica set `rs.status()`:
```
// Node 1
"stateStr" : "PRIMARY",

// Node 2
"stateStr" : "SECONDARY",
```

---

Hints on setting up replica set:

1. Make sure replica set is initiated with `rs.initiate(config)` with success  

```
// Step-1
Assuming proddb1 and proddb2 up and running as single server

// Example:
mongod --replSet prod --dbpath ... --port 27017      // proddb1 
mongod --replSet prod --dbpath ... --port 27017      // proddb2

// Step-2
Connect to proddb1 or proddb2

$ config = {_id:"prod", members: [
{_id: 0, host: "proddb1:27017"},
{_id: 1, host: "proddb2:27017"}]
};

$ rs.initiate(config);  
// This command should return positive result like ok or 1

$ rs.status()
// After couple of minutes nodes should be primary and secondary
```

2) Make sure nodes and set name (`prod` in your case) are correctly entered on Robo 3T

3) Also see https://docs.mongodb.com/manual/tutorial/deploy-replica-set/

**Comment by mssatheesh87** [comment]
If i give it showing it already initialized .. should i remove and do .. if it is  how ?

[root@proddb1 ~]# mongo --host proddb1 -u admin -p'xxxxxxx' --authenticationDatabase admin
MongoDB shell version v3.4.5
connecting to: mongodb://proddb1:27017/
MongoDB server version: 3.4.5
prod:RECOVERING>  config = {_id:"prod", members: [
... {_id: 0, host: "proddb1:27017"},
... {_id: 1, host: "proddb2:27017"}]
... };
{
        "_id" : "prod",
        "members" : [
                {
                        "_id" : 0,
                        "host" : "proddb1:27017"
                },
                {
                        "_id" : 1,
                        "host" : "proddb2:27017"
                }
        ]
}
prod:RECOVERING> rs.initiate(config);
{
        "info" : "try querying local.system.replset to see current configuration",
        "ok" : 0,
        "errmsg" : "already initialized",
        "code" : 23,
        "codeName" : "AlreadyInitialized"
}

**Comment by mssatheesh87** [comment]
If i disable authentication and restart service on both ... It showing fine as below ...

            {
                        "_id" : 0,
                        "name" : "proddb1:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",

                {
                        "_id" : 1,
                        "name" : "proddb2:27017",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
       
        "ok" : 1


I am not sure what is the problem i am making ...

**Comment by simsekgokhan** [comment]
Hi @mssatheesh87 , do you still have this problem?
