### ISSUE TITLE
Can't access connection settings modal, after switching windows 

### ISSUE THREAD

**Issue by euqen** [Studio3T/robomongo#1397]
OS: Mac OS Sierra 12.12.5
Robomongo: Robo 3T 1.1

I'm not able to edit connection settings after switching to another window or moving to next desktop. Seems this modal window loses focus and goes behind available connections window.

![jun-29-2017 15-25-18](https://user-images.githubusercontent.com/1840226/27687358-3c5683a6-5cdf-11e7-95aa-6fdcfb86d8cd.gif)

**Comment by juliashibalko** [comment]
Hi @euqen, thanks for reporting! We reproduced the issue, so will consider to fix it in further releases. It's connected to issues with Qt and Mac OS code. We will get back to you with any updates.

**Comment by simsekgokhan** [comment]
This should be solved in latest version, pls feel free to re-open if you still have the problem ;)
