### ISSUE TITLE
Add line numbers to the UI

### ISSUE THREAD

**Issue by Dane411** [Studio3T/robomongo#1399]
When an error happens, it refers to some line, but there's no other way to find out which line is it but to count all the way down to it.

**Comment by simsekgokhan** [comment]
Hi @Dane411 , is the following option enabled? 
`Options - > Show Line Numbers By Default`

**Comment by Dane411** [comment]
My apologies. I'm sure I looked for it and didn't find it, but now I checked both Robo 3T and Robomongo 1.0.0, and it's there, dunno how could I've missed it.  How embarrassing! 😳
Thanks for the help!!!

PS: Feel free to remove this post :)

**Comment by simsekgokhan** [comment]
Not a problem at all :)

**Comment by invegat** [comment]
For Robo3T 1.2 <crtl>F11 toggles line numbers.

**Comment by nituis** [comment]
after selected "Show Line Numbers By Default"
still no any line numbers on query area

Robo 3T version 1.3.1
