### ISSUE TITLE
Script execution

### ISSUE THREAD

**Issue by callupio** [Studio3T/robomongo#1403]
HI all,

it would be possible to display the results of multiple queries in only one result pane?

"Count of a"
db.a.count()
"Count of b"
db.b.count()
"Count of c"
db.c.count()
"Count of d"
db.d.count()

produces 8 panel that moreover are not vertically scrollable.

Thanks

**Comment by simsekgokhan** [comment]
Hi @callupio , I think this does not solve your problem completely. But tabbed output design can at least solve the vertically non-scrollable problem. Please see: https://github.com/Studio3T/robomongo/issues/1591#issuecomment-466630423
