### ISSUE TITLE
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer

### ISSUE THREAD

**Issue by perlun** [Studio3T/robomongo#1404]
I just did a fresh install on a Windows 2012 R2 server, and the program crashed the first time I ran it ("An error has occurred in the program"). The next time I try to run it, I get this problem:

```
---------------------------
robo3t.exe - System Error
---------------------------
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

**Comment by perlun** [comment]
(Uninstall/reinstall didn't help, not even re-downloading. Also tried the portable version to no avail.)

Download Visual C++ redist from [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145) worked. If this is a prerequisite, perhaps it needs to be more clearly stated? (If it, please forgive me; I didn't see it mentioned on the [download page](https://robomongo.org/download).)

**Comment by juliashibalko** [comment]
Hi @perlun, thanks for reporting issue!
This is known issue and related to Windows update problems. So simply follow the link https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows, install update and Robomongo will launch.
Please lat us know how it went.

**Comment by perlun** [comment]
OK, thanks @juliashibalko. I already solved it, but if it's a known issue, let's just close this GH issue. People who run into it can google for this GitHub issue and find the solution here. 👍

**Comment by barman47** [comment]
How did you solve it please? Been having the same issue on my Windows 8.1 x64

**Comment by Reeta29** [comment]
Hii to all when i tried to install mongodb in my it is showing error as shown in screenshot.can ayone help me to so;ve this problem
![screenshot 42](https://user-images.githubusercontent.com/42059168/43630950-9cab8e38-96b6-11e8-9ffb-06f38bfdb1e3.png)
