### ISSUE TITLE
 Qt platform plugin "xcb" issue when running.

### ISSUE THREAD

**Issue by murshid1988** [Studio3T/robomongo#1409]
I have downloaded the build '`robo3t-1.1.1-linux-x86_64-c93c6b0`' in my Ubuntu 17.04 and when I try to run I am receiving this error.

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

Is this is an issue that should be fixed from my side?

**Comment by Grummfy** [comment]
see #1392 and #1385

solution => https://github.com/Studio3T/robomongo/issues/1385#issuecomment-314894980

**Comment by murshid1988** [comment]
Thanks. Will look into it

**Comment by murshid1988** [comment]
Worked. Thanks.
