### ISSUE TITLE
font too small on a 4k monitor

### ISSUE THREAD

**Issue by axe-z** [Studio3T/robomongo#1425]
this would be good to be able to get the font larger, these days we need to be able to adjust .

**Comment by andrey-cabonline** [comment]
Under linux(qhd+ 3200x1800) there is a solution - set env variables:
```bash
QT_SCALE_FACTOR=2 QT_AUTO_SCREEN_SCALE_FACTOR="0"
```

then scaling works.

@axe-z probably the same settings might help you as well.
But it would be nice to make it work out of the box of course.

**Comment by axe-z** [comment]
i'm back with compass.. too late

**Comment by simsekgokhan** [comment]
Hi @axe-z, feel free to re-open if you still have the problem with latest version.

**Comment by Delagardi** [comment]
> feel free to re-open if you still have the problem with latest version.

Hi @simsekgokhan 

I have the latest version of Robo 3T. But there is a problem with 4k display (laptop, linux Manjaro)

Is there a way to fix this now?

![image](https://user-images.githubusercontent.com/1944217/128605644-7b127c69-8820-4b09-b960-2c9518628bf2.png)
