### ISSUE TITLE
Duplicated ObjectID in query result

### ISSUE THREAD

**Issue by houjunchen** [Studio3T/robomongo#1428]
In Robo 3T, I got two duplicated records when I query by `ObjectId`:
![image](https://user-images.githubusercontent.com/5383325/29705046-ee525480-89ae-11e7-9f7b-ca418dee91f3.png)

But I will get one record if I use `memberID` in `match`.

The result I got from mongo shell is expected:
![image](https://user-images.githubusercontent.com/5383325/29705062-049f4bee-89af-11e7-8371-84eaf23d0fca.png)

**Comment by simsekgokhan** [comment]
Hi @houjunchen , feel free to re-open if you still have the problem with latest version. We are unable to reproduce.
