### ISSUE TITLE
Error when inserting Documents with for Loop

### ISSUE THREAD

**Issue by iwaynee** [Studio3T/robomongo#1431]
Is this a bug?
[https://stackoverflow.com/questions/45954706/error-when-inserting-documents-with-for-loop](https://stackoverflow.com/questions/45954706/error-when-inserting-documents-with-for-loop)

I use Robo 3T 1.1.1, MongoDB 3.4, Windows 7 and I get exactly 1 of 4 times I run the script this Error.

**Comment by simsekgokhan** [comment]
Hi @iwaynee , feel free to re-open if you still have the problem with latest version.
