### ISSUE TITLE
Error: Resource temporarily unavailable. when a identity file is used but a username isn't.

### ISSUE THREAD

**Issue by jdalegonzalez** [Studio3T/robomongo#1433]
Configure a connection to use an ssh tunnel.
Leave the username field blank (ssh will work fine)
You get the following error...
Error: Resource temporarily unavailable. Authentication by key (xxxx) failed (Error -18). (Error #35)

The work-around is to use a username.

**Comment by simsekgokhan** [comment]
Hi @jdalegonzalez , please see the beta for this problem here: https://github.com/Studio3T/robomongo/issues/1125#issuecomment-353274408
