### ISSUE TITLE
Cannot connect via SSH after upgrading to WHM/Cpanel v66

### ISSUE THREAD

**Issue by kaizen-soze** [Studio3T/robomongo#1440]
I'm running WHM/Cpanel on CentOS server. Cpanel recently upgraded itself to version 66, and the SSH tunnel option has stopped working. I reverted to a backup from the previous week, and the SSH tunnel began working again.

<img width="1383" alt="screenshot 2017-09-19 21 59 57" src="https://user-images.githubusercontent.com/28831947/30623592-89453ce2-9d86-11e7-87e7-f80fb286b53d.png">

<img width="1293" alt="screenshot 2017-09-19 22 03 04" src="https://user-images.githubusercontent.com/28831947/30623596-8eb3af88-9d86-11e7-8acc-ce28133499be.png">

**Comment by simsekgokhan** [comment]
Hi @kaizen-soze, unfortunately Centos is not supported currently.
https://github.com/Studio3T/robomongo#supported-platforms
I suggest to create a new ticket to request this support and upvote.

There is SSH upgrade on v1.4 which you can also try.
