### ISSUE TITLE
Menus and context menus disposition with multi-monitor setup

### ISSUE THREAD

**Issue by tsabolov** [Studio3T/robomongo#1441]
I am using Robo 3T 1.1.1 on Linux Fedora 26 with GNOME on Xorg. I am using two monitors which are shifted relative to each other (the right one is a little bit higher than the left one).
Now, I open Robo 3T on the right monitor (which is higher). After that when I click any menubar item, or right-click element in the explorer pane, then the menu popup appears displaced (see attachments). The upper boundary of the menu popup is exactly at the top boundary of the left monitor.
My guess is that the first monitor's dimensions are used to calculate the position of menus.

![screenshot from 2017-09-27 09-34-10](https://user-images.githubusercontent.com/1006564/30901185-185a9f90-a367-11e7-8f5e-f3bbca35861c.png)
![screenshot from 2017-09-27 09-34-30](https://user-images.githubusercontent.com/1006564/30901193-1bc6c01e-a367-11e7-8e54-3f4a87e228c4.png)

**Comment by simsekgokhan** [comment]
Hi @tsabolov , unfortunately this OS is not supported currently.
https://github.com/Studio3T/robomongo#supported-platforms

I suggest to create a new ticket to request support for this OS and upvote.
