### ISSUE TITLE
MongoDB Connection: editing a new replica set connection doesn't save properly 

### ISSUE THREAD

**Issue by DanStach** [Studio3T/robomongo#1445]
version: Robo 3T 1.1.1 (macOS sierra 10.12.6)
when editing a previously saved replica set the last entry doesn't save properly. There is a workaround (change the name of connection to force a save)

steps:
- open robomongo
- file: connection
- click create
- enter info (type = replica set, name = new rep, add 3 members)
- save
- edit connection
- change last 2 members 
- save
- edit connection (to verify member names)

issue: last member name did not change.

Video of issue: http://d.pr/v/X4fe3U/4e3VzRbW

**Comment by DanStach** [comment]
this might relate to #1395

**Comment by simsekgokhan** [comment]
Hi @DanStach , feel free to re-open if you still have the problem with latest version.
