### ISSUE TITLE
Save and load connection details

### ISSUE THREAD

**Issue by c0mrade** [Studio3T/robomongo#1446]
Would be nice if this was possible. I m currently working on a db that is hidden behind several firewalls, and I have to use a 'jumpbox' in between, which is like a temporary VM that can disappear anytime, and having not to setup connections again would be great

**Comment by xGanimeDx** [comment]
Hello @c0mrade, all information related to connections is stored in _robo3t.json_ file, location for this file:
1. Linux/MacOS: ~/.3T/robo-3t/*version*/
2. Windows: C:\Users\*userName*\.3T\robo-3t\*version*\

**Comment by simsekgokhan** [comment]
Also see: https://github.com/Studio3T/robomongo/wiki/Robomongo-Config-File
