### ISSUE TITLE
Batch size works inconsistently

### ISSUE THREAD

**Issue by sedge** [Studio3T/robomongo#1456]
Changing the batch size on simple queries sometimes doesn't work, and there's no error feedback about why. It simply resets after running the query. Here's a gif of it not working on a collection it has worked on before:

![batch_size](https://user-images.githubusercontent.com/1616860/31824868-61531500-b57e-11e7-876c-67a3795cee27.gif)

**Comment by simsekgokhan** [comment]
Hi @sedge , feel free to re-open if you still have the problem with latest version.
