### ISSUE TITLE
Mouse cursor is really difficult to see in the document editor (macOS)

### ISSUE THREAD

**Issue by pqvst** [Studio3T/robomongo#1457]
Where's ~~Waldo~~ the mouse cursor? It's ridiculously difficult to see the mouse cursor when editing documents. I'm not sure if this is a macOS specific issue. I haven't tested on other platforms.

![screenshot 2017-10-21 21 07 22-a](https://user-images.githubusercontent.com/4990657/31851662-68cea52e-b6a5-11e7-8147-2fcf101ffbba.png)

I'd expect the mouse cursor to invert/change color on dark backgrounds.

Spoiler below:

![screenshot 2017-10-21 21 09 51-b](https://user-images.githubusercontent.com/4990657/31851663-6e1a22c4-b6a5-11e7-9a46-3c2c88e7a73f.png)

**Comment by simsekgokhan** [comment]
Hi @pqvst , feel free to re-open if you still have the problem with latest version.
