### ISSUE TITLE
How to install Robo 3T on Ubuntu 17.10?

### ISSUE THREAD

**Issue by PedroFumero** [Studio3T/robomongo#1458]
I want to install Robo 3T, I downloaded the file **robo3t-1.1.1-linux-x86_64-c93c6b0.tar.gz** from the official website, and I have unzipped it, but upon entering the **bin** folder, and clicking on the **robo3t** file , nothing happens. Does anyone know how I can install it on Ubuntu 17.10?

**Comment by xyyy1719** [comment]
Run ./robo3t from the terminal.
If see issue regarding the Qt platform plugin "xcb"..., check the solution from Nicolab as below:
[issue#1450](https://github.com/Studio3T/robomongo/issues/1450)
This solves my problem.

**Comment by rodrigogs** [comment]
It doesn't work for me
![captura de tela de 2018-01-12 10-45-44](https://user-images.githubusercontent.com/2362425/34875767-d19f54e2-f785-11e7-9d91-c8bab994dceb.png)

**Comment by solofeed** [comment]
The same problem.

**Comment by welder496** [comment]
I installed Robo3t in 17.10 and was necessary Qt for this, as shown above!!

**Comment by welder496** [comment]
But, I finished an install now, and the problems were solved. I was done in Xubuntu 17.10
