### ISSUE TITLE
Crashes on macOS High Sierra  version 10.13.1 (17B48)

### ISSUE THREAD

**Issue by witeX** [Studio3T/robomongo#1466]
I had issue with running Robo 3T 1.1.1

After installation I have crash.

Also error with previously installed Robomongo

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x3842800:
--> 
    __TEXT                 000000010c988000-000000010d6b4000 [ 13.2M] r-x/rwx SM=COW   [`]

Application Specific Information:
objc_msgSend() selector name: _recursiveFindDefaultButtonCell

Applications runs fine from terminal '/Applications/Robo\ 3T.app/Contents/MacOS/Robo\ 3T'
Or '/Applications/Robomongo.app/Contents/MacOS/Robomongo'
Also after running application from terminal it's start to launch fine from launchpad or from Finder and work fine. Only new Robo 3T.`

**Comment by cyriltvarghese** [comment]
Hi. I dont know the solution to your problem. However I want to ask you,have you observed any reduction in battery life? My battery has been draining faster after updating to 10.13.1.

**Comment by maggiben** [comment]
Same story... and to make things worse the new version isn't certified...

**Comment by jackmiller334** [comment]
I'm also experiencing the same issue. High Sierra 10.13.1 (17B48)

**Comment by tomasznaumowicz** [comment]
Thank you for reporting. It's on our list for the next release and we're looking into it. It's difficult to reproduce at the moment but we are collecting error reports.
We will be updating the ticket https://github.com/Studio3T/robomongo/issues/1412 on this issue.

**Comment by simsekgokhan** [comment]
Hi All, please see the comment and Robo 3T 1.2 - Beta installer here: https://github.com/Studio3T/robomongo/issues/1412#issuecomment-353276002. Thanks.
