### ISSUE TITLE
Crashes every time after editing a document on a replica set

### ISSUE THREAD

**Issue by adamreisnz** [Studio3T/robomongo#1469]
No error, just crashes. OS X.
Happens every time. Then works ok after restart.

**Comment by vlsd** [comment]
I get the same behavior when editing a collection (either changing its name, dropping it, or creating a new one). The edit goes through, but the app crashes and needs to be restarted.

**Comment by Goostavo** [comment]
The same on Ubuntu 17.10 running RoboMongo 1.2.1;

RoboMongo 1.1.1 don't have this error. Works well.

**Comment by charlieman** [comment]
Maybe this is related to my case, Robo.* 1.2.1 crashes when I try to edit a record right after I edited one and before it reloaded the query. If I wait a couple of seconds (and see it flicker) then it doesn't crash.

**Comment by simsekgokhan** [comment]
Hi guys, feel free to re-open if you still have the problem with latest version.
