### ISSUE TITLE
crash when open

### ISSUE THREAD

**Issue by maxlibin** [Studio3T/robomongo#1473]
looks like does not support MacOS high sierra? whenever i open it crashes.

**Comment by sizovilya** [comment]
+ 1, same problem.

**Comment by tianp** [comment]
I confirmed that this also happens to me. MacOS High Sierra.

**Comment by tianp** [comment]
Update: after installing the latest version Robo 3T, it's now working on MacOS High Sierra.

**Comment by simsekgokhan** [comment]
Hi All, we have a beta to test this problem, please see it here: https://github.com/Studio3T/robomongo/issues/1412#issuecomment-353276002

**Comment by maxlibin** [comment]
Beta 1.2 works fine 👍
