### ISSUE TITLE
Robomongo is not connecting to MongoDB 3.4.10 using SSL

### ISSUE THREAD

**Issue by amitroy1234u** [Studio3T/robomongo#1474]
I have installed mongodb-win32-x86_64-2008plus-ssl-3.4.10-signed.msi and robo3t-1.1.1-windows-x86_64-c93c6b0.exe and run the Mongod and Mongo service. Now I am trying to create connection to Mongo DB to robomongo as follows. 
![mongo1](https://user-images.githubusercontent.com/33865947/33072599-3034d11c-cee6-11e7-9529-bcf552b1c90b.PNG)
Now after providing the details I am going to SSL tab. Checking the use SSL protocol checkbox. selecting authentication method as self signed certificate, I am click on test. It is showing the below error.
![image](https://user-images.githubusercontent.com/33865947/33072762-b9b23fba-cee6-11e7-913c-59abba5a79ec.png)

If I am not using the SSL protocol, it is connecting fine.
![image](https://user-images.githubusercontent.com/33865947/33072852-058e14cc-cee7-11e7-91af-f23b762da195.png)

I need SSL connection as per my client requirements. Help would be very much appreciated 

FYI -  mongodb-win32-x86_64-2008plus-ssl  supports SSL as per Mongo DB site

**Comment by simsekgokhan** [comment]
Hi @amitroy1234u , feel free to re-open if you still have the problem with latest version.
