### ISSUE TITLE
Support for MongoDB 3.6, arrayFilters

### ISSUE THREAD

**Issue by vilinski** [Studio3T/robomongo#1477]
Hi,

it seems the project is dead, but may be we have luck and you'll make one more release for 3.6.
Looking at last commits, it should be 1.2?

Currently the new 3.6 feature `arrayFilters` doesn't work. 
This query works in mongo shell:

```js
db.Products.update(
    {"productId": 12345},
    {$set: {"nationalData.$[elem].groupId": 9999}},
    {"arrayFilters": [{"elem.country": "AT"}], 
     "multi": true  }
)
```

> `WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })`

But from robomongo comes an error:
> `No array filter found for identifier 'elem' in path 'nationalData.$[elem].groupId'`

**Comment by Albert-Bujanovs** [comment]
Just tried the latest version 1.2.1 still strips the "arrayFilters" from the options document.

**Comment by anthonybarbatto** [comment]
And here I am thinking I was doing something wrong with my arrayFilters query. 😀 

Maybe they'll add a preference similar to what their Studio product has?

![preferences 2018-07-22 13-41-42](https://user-images.githubusercontent.com/744609/43049924-0077a6b4-8db5-11e8-943e-c8a740f641f1.jpg)

**Comment by vilinski** [comment]
not sure they add anything. For my not frequent experiments with a pipeline, I'm currently using slow, buggy but also free and uptodate ~js-crap~ [Mongo-compass](https://docs.mongodb.com/compass/)

**Comment by vilinski** [comment]
![image](https://user-images.githubusercontent.com/259479/50225590-46907100-03a1-11e9-9a6b-0f3664460f49.png)

**Comment by mariuswang007** [comment]
Robo 3T, 2 years gone, this issue still be here and not fixed.  Is there anyone know if Robo Studio has the same issue too?

**Comment by vilinski** [comment]
@mariuswang007 already tried 1.3?

**Comment by Maxeh** [comment]
It is working now in Robo3T 1.4

**Comment by vilinski** [comment]
in Robo3T 1.4 mongo shell is upgraded to 4.2

**Comment by vilinski** [comment]
in Robo3T 1.4 mongo shell is upgraded to 4.2
