### ISSUE TITLE
Bad UI (text) rendering

### ISSUE THREAD

**Issue by avivace** [Studio3T/robomongo#1481]
![image](https://user-images.githubusercontent.com/14352721/33937299-306f652e-e003-11e7-8a12-b7803d55e9dd.png)
Debian Sid, qt should be okay on the system, doesn't happen with any other Qt4 or Qt5 application.

**Comment by simsekgokhan** [comment]
Hi @avivace , unfortunately this OS is not supported currently.
https://github.com/Studio3T/robomongo#supported-platforms

I suggest to create a new ticket to request support for this OS and upvote.
