### ISSUE TITLE
Robo3T does not start under wayland

### ISSUE THREAD

**Issue by wandi34** [Studio3T/robomongo#1482]
Hi. I am using opensuse Tumbleweed with wayland and want to use Robo3T 1.1 (latest version). Unfortunately I cannot start Robo3T because of the following error:

This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: xcb.

Any help?

**Comment by simsekgokhan** [comment]
Hi @wandi34 , thanks for reporting the problem.
Can you try with Robo 3T 1.2 - Beta here: https://github.com/Studio3T/robomongo/issues/1385#issuecomment-353275110 ?
And the other solution is here: https://github.com/Studio3T/robomongo/issues/1385#issuecomment-310014331.

**Comment by wandi34** [comment]
Hi @simsekgokhan, unfortunately I still get the same error.

Tried the beta and tried your solution in the other thread. Both bring the same error.

**Comment by simsekgokhan** [comment]
@wandi34 , thanks for the quick test. Then, it might be another root cause, we will have to investigate. 
For now, other options are trying different Robo versions or installing/uninstalling some Qt elements on your system.

**Comment by pricetula** [comment]
I tried this with ubuntu 17.10 gives below error
```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.
```

**Comment by simsekgokhan** [comment]
Hi @pricetula , thanks for reporting the problem.
Are you trying Robo 3T 1.2 Beta? I just tried and it worked for me on Ubuntu 17.10.
Please see: [Robo 3T 1.2 Beta](https://github.com/Studio3T/robomongo/releases/tag/v1.2.0-beta)

**Comment by pricetula** [comment]
Thanks @simsekgokhan 1.2 Beta works perfectly

**Comment by Cabezaa** [comment]
i had the same problem that  @pricetula in Elementary OS,   and the beta 1.2 has resolve this. Thanks!
