### ISSUE TITLE
Crash when returning from lost connection

### ISSUE THREAD

**Issue by drc-gcoakley** [Studio3T/robomongo#1483]
My company configures all systems with a roaming network profile. (Which is horrible for any developer.) When I leave the office, I hibernate my computer which is often when Robo-3T is open and has 1+ connections to databases open *and* mongo code in multiple tabs.  Often when I wake the laptop from hibernate, which may be at home or at the office again, Robo-3T will crash. It does this without any means for recovering the mongo code which I may not be saved. 

I try to remember to close Robo-3T but, often forget. Robo-3T should recover from a lost connection more gracefully (it is a network connection after all.) [Issue #340](https://github.com/Studio3T/robomongo/issues/340) would help this situation immensely as well as most in most other cases when Robo-3T crashes.

**Comment by simsekgokhan** [comment]
Hi @drc-gcoakley , we already have related fixes, feel free to re-open if you still have the problem with latest version.
