### ISSUE TITLE
Unable to access robo 3t in Dell laptop

### ISSUE THREAD

**Issue by Ankaushik** [Studio3T/robomongo#1488]
I am unable to create the connection in the Robo 3t .When I am creating the connection it is giving error that mongoDB management tool has stopped working.

I attached the error what I am facing. Kindly check the issue as soon as possible.

![image001](https://user-images.githubusercontent.com/35332350/34822024-8c2e2838-f6eb-11e7-9929-3380340d17e3.jpg)

**Comment by simsekgokhan** [comment]
Hi @Ankaushik. Feel free to re-open if you still have the problem with latest version.
