### ISSUE TITLE
New Connection dialog

### ISSUE THREAD

**Issue by Alishankhan** [Studio3T/robomongo#1497]
New connection dialog is too long  and unable to resize it.
![screenshot from 2018-01-30 15-49-30](https://user-images.githubusercontent.com/1307689/35561081-363b47dc-05d5-11e8-96d7-2d9664734b32.png)

**Comment by xGanimeDx** [comment]
Hello @Alishankhan, is it Studio 3T not Robo 3T? If so better to send it to https://studio3t.com/feedback/ since this repo related only to Robo 3T project
