### ISSUE TITLE
Cannot close the app

### ISSUE THREAD

**Issue by rastko-florencehc** [Studio3T/robomongo#1499]
Using robo mongo on Mac 10.11.6 and cannot close the app gracefully

![screen shot 2018-02-01 at 11 00 44 am](https://user-images.githubusercontent.com/25254648/35672695-9d23fd0c-073f-11e8-91a3-6536da855bf8.png)

**Comment by juliashibalko** [comment]
@rastko-florencehc I suppose you have the windows with Connection manager opened. That can be the reason why you can't quit Robo3t.

**Comment by rastko-florencehc** [comment]
@juliashibalko unfortunately no... This is not a constant behavior btw. It's random.

**Comment by rastko-florencehc** [comment]
Ok, I think I know what is the issue: 

Whenever there is any Robo3t modal opened you cannot close the app. 

It must have been that I've never tried to close it before while modal dialog was opened. But having some connection issues at the moment revealed this behavior...
