### ISSUE TITLE
Cannot run in CentOS 7.x

### ISSUE THREAD

**Issue by lkf2738** [Studio3T/robomongo#1512]
What kind of library need to install for CentOS 7 to run robo3T?  Always claimed the version `GLIBC_2.18' not found

**Comment by altmind** [comment]
the latest version of robomongo that can run on centos 7.5 is "1.0.2 - Patch version with ECMAScript 2015 (ES6) Support" @ https://github.com/Studio3T/robomongo/releases

i see no rationale why robo3t/robomongo decided to build on newer glibc abandoning the support of **current** versions of centos and rhel.

glibc in centos is not ancient and is actively supported with a lot of backporting.

**Comment by swateek** [comment]
0.8.1 was working, where can I find the prior version of the distributions?

**Comment by njordr** [comment]
I found a workaround creating a docker image to run robo3t: https://hub.docker.com/r/njordr/robo3t

Hope it could help

**Comment by kwill4026** [comment]
thanks will try this and see in an docker ubuntu base build or redhat base build. @njordr

**Comment by kwill4026** [comment]
@njordr so this worked for me. I used ubuntu:18.04 as the base image.
One question though. What exactly are the following env variables doing when running the docker run command: 
 --env="DISPLAY" 
 --volume="$HOME/.Xauthority:/root/.Xauthority:rw" 
  -v "$HOME/data/robo3t/3T:/root/.3T" 
  -v "$HOME/data/robo3t/config:/root/.config/3T"

**Comment by njordr** [comment]
@kwill4026 
`DISPLAY` var is used to export your display to the container, so it will know which display to use
`$HOME/.Xauthority:/root/.Xauthority:rw` is for auth in xorg subsystem
`$HOME/data/robo3t/3T:/root/.3T` and `$HOME/data/robo3t/config:/root/.config/3T` are used to save your preferences and connections between container restarts

**Comment by kwill4026** [comment]
thanks for the explanation! @njordr

**Comment by Pupkur** [comment]
Hello. 
Where can I get Robo 3T 1.0.2? I can`t use docker for some reasons.

**Comment by njordr** [comment]
@Pupkur try here: https://github.com/Studio3T/robomongo/releases

**Comment by simsekgokhan** [comment]
Hi all, unfortunately Centos is not supported currently.  
https://github.com/Studio3T/robomongo#supported-platforms

I suggest to create a new ticket to request this feature and upvote.
