### ISSUE TITLE
Keyboard Layout US-int not accept accents

### ISSUE THREAD

**Issue by rogeriomq** [Studio3T/robomongo#1516]
S.O: Fedora 27 64 bits with locale PT_BR (Brazil)
Hardware: DELL XPS 13 (Keyborad US-int )

In editor not accept accents(", ') with layout keyboard US_int, only PT_br.

I remember that OnlyOffice also had this same error, but it was fixed in the latest version.

**Comment by simsekgokhan** [comment]
Hi @rogeriomq , thanks for reporting the problem and sorry for answering so late.
Fedora is currently is not supported. -> https://github.com/Studio3T/robomongo#supported-platforms
