### ISSUE TITLE
Validate database naming convention before database is created.

### ISSUE THREAD

**Issue by frankodoom** [Studio3T/robomongo#1525]
Robomongo accepts and saves db.example as a valid database name, when you attempt to carry out an operation on the database then you are informed it is invalid. Validations should be done before database is saved into Mongo.

**Comment by simsekgokhan** [comment]
Hi @frankodoom , thanks for reporting the problem and sorry for answering so late. 
What you explain is how MongoDB works (you can try with mongo shell). We try to keep Robo as identical as mongo shell.
