### ISSUE TITLE
Unable to connect ssh using ecdsa key

### ISSUE THREAD

**Issue by xavi-dev** [Studio3T/robomongo#1530]
This is the error:

`Resource temporarily unavailable. Authentication by key (~/.ssh/id_ecdsa) failed (Error -16). (Error #35)`

**Comment by simsekgokhan** [comment]
Hi @xavi-dev , thanks for reporting the problem and sorry for answering so late.  

On Windows & macOS, we have upgraded our SSH library to the latest version (libssh2 v1.9.0 - Jun/2019) and it supports ECDSA and Ed25519 keys. Also during development, we saw that the upgrade fixed some problematic cases. 
I hope Robo 3T 1.4 will fix some of your problems -> [Robo 3T 1.4](https://github.com/Studio3T/robomongo/releases/tag/v1.4.0)

Please also see: https://github.com/Studio3T/robomongo/issues/1189#issuecomment-447109457 and https://github.com/Studio3T/robomongo/issues/1590#issuecomment-475954939
