### ISSUE TITLE
Running RoboMongo under multiple users on a Windows 10 installation

### ISSUE THREAD

**Issue by laredoza** [Studio3T/robomongo#1537]
Hi,

I have two accounts on a Windows 10 laptop ( Personal, and Domain). RoboMongo is running fine on the personal account. On the Domain account, I get stuck on the Eula page:

![image](https://user-images.githubusercontent.com/5489412/39667060-34a7e4c4-50ae-11e8-9c0f-178c78023a2d.png)

I've recreated this on another machine where I used two local accounts.

**Comment by laredoza** [comment]
Never mind, this is actually a non issue and a mistake from my side.

**Comment by mrblanchett** [comment]
How did you manage to solve the issue? I only have a single account on my PC and yet can't get past this window

**Comment by SuperKirik** [comment]
I  suddenly  have faced the same issue on mac (a single account as well).
