### ISSUE TITLE
Copy value of document field has bom on mac

### ISSUE THREAD

**Issue by kaifei-bianjie** [Studio3T/robomongo#1539]
> when i copy value of a document field which type is string，paste it on my ide，i find it has bom before string。
Does this happened to anyone ?
---
> Robo 3T version: 1.2.1
Macos version: 10.13.4
Mongodb version：3.6.4

**Comment by antontolken** [comment]
confirmed: i have the same problem

Robo 3T: 1.2.1
macOS: 10.13.3
MongoDb: 3.6.5

**Comment by antontolken** [comment]
why was it closed without giving the reason?
