### ISSUE TITLE
Ignore this

### ISSUE THREAD

**Issue by GBGitUser** [Studio3T/robomongo#1545]
Hi, I just upgraded to High Sierra and posted a weird issue that I had with RoboT. Only it WASN'T a problem with RoboT. High Sierra had reset my mouse as I had to blow everything away and by default right click was not enabled. As such, what I thought was a strange thing in that I could no longer right click and refresh or disconnect was not a problem with RoboT but was a problem with my mouse after re-installing my OS.

Sorry everyone - please ignore! I would delete this issue if I could! High Sierra has been killing me for the last 24 hours! :[

**Comment by xGanimeDx** [comment]
@GBGitUser hello, if there is no problem you can close this ticket :)
