### ISSUE TITLE
unable to start robo3t 121 on mac 

### ISSUE THREAD

**Issue by nanorobogit** [Studio3T/robomongo#1548]
Report from App launch
Process:         Robo 3T [2588]
Path:            /Applications/Robo 3T.app/Contents/MacOS/Robo 3T
Identifier:      com.3tsoftwarelabs.robo3t
Version:         ??? (1.2.1)
Code Type:       X86-64 (Native)
Parent Process:  launchd [149]
Responsible:     Robo 3T [2588]
User ID:         501

**Comment by AbdulWahab0** [comment]
Solution Please

**Comment by xGanimeDx** [comment]
@nanorobogit @AbdulWahab0 which OS (name/version/build) do you use?

**Comment by AbdulWahab0** [comment]
@xGanimeDx Thanks for your reply .The Problem is solved right now after updating my mac
