### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by simison** [Studio3T/robomongo#1550]
Hello!

I appreciate Studio 3T has put some effort into maintaining this project. Thanks!

It's looking a bit worrying right now, however — activity has been near zero since Feb 2018 (it's June now).

Has this project been abandoned?

If the plan is to keep this project alive — what's the roadmap for future? Plans for MongoDB ver 3.5 and 3.6 support? Triaging 551+ issues piling up more every week?

If there is no plan, it would look like this project has become just an advertisement for the commercial project you guys run. Hope that's not the case. :-)

Thanks for answering these questions! Cheers. <3

**Comment by noqcks** [comment]
Another user here,  echoing your concerns. I'm hoping for 3.6 support soon...

**Comment by snarlynarwhal** [comment]
They killed it to push the paid version. Latest version has invited more bugs than features :/

**Comment by simison** [comment]
Adding the response I got via email:

> _we're fully committed to ensuring it remains up to date and compatible with MongoDB. in 2018 we've made and released several updates to support MongoDB 3.4, and support for 4.0 is on our development roadmap._

**Comment by tomasznaumowicz** [comment]
@simison thank you for posting the reply here, I was about to comment as well.

As stated above, we're fully committed to supporting Robo 3T and keeping it up to date and compatible with MongoDB.

As with every release of Robo 3T, we're also addressing selected issues reported via github.

**Comment by simison** [comment]
Thanks, @tomasznaumowicz :-)

Do you have plans to allocate resources in developing new features and do bug-fixing for the client outside MongoDB compatibility work?
