### ISSUE TITLE
Robo 3T The input space causes the remote login to fail

### ISSUE THREAD

**Issue by Cydmi** [Studio3T/robomongo#1551]
Enter a space at the end of the address, causing the login to fail.
Expect to add the ability to remove Spaces。
![2018-06-16 11 13 23](https://user-images.githubusercontent.com/9507388/41495329-36383310-7157-11e8-8247-141ed74ba238.png)

**Comment by simsekgokhan** [comment]
Hi @Cydmi , thanks a lot for your suggestion. We have included this fix into next release version 1.3.

**Comment by simsekgokhan** [comment]
Robo 3T 1.3 Beta is ready for resting. 
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

Feel free to open the ticket if you find problem in Beta.
