### ISSUE TITLE
Support for creating version 4 UUID

### ISSUE THREAD

**Issue by andidev** [Studio3T/robomongo#1554]
`newUUID` in [uuidhelpers.js](https://github.com/Studio3T/robomongo/blob/0e8cd5cefc0ad2c7816ef68ed8a566ff689cca1f/src/robomongo/gui/resources/scripts/uuidhelpers.js#L55) should support creating version 4 UUIDs.

Mongodb supports creating UUIDs by `UUID()` ([see UUID doc](https://docs.mongodb.com/manual/reference/method/UUID/)) since version 3.6

I'm trying to replace ids with new UUID and cant seem to do so since I get `TypeError: uuid is undefined`

![skarmavbild 2018-06-25 kl 10 24 51](https://user-images.githubusercontent.com/571389/41838945-1c285466-7862-11e8-84bb-e208216a81ba.png)

**Comment by Babbel404** [comment]
I'm having the same issue on v1.2.1, does anyone have an update on this problem?

**Comment by simsekgokhan** [comment]
Hi All, thanks for reporting the problem. 
Can you please try our beta? We have a fix for this problem, hopefully it will work.

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

**Comment by andidev** [comment]
Works like a charm!!! Thanks!
