### ISSUE TITLE
Can I change shell script code style? 

### ISSUE THREAD

**Issue by mrdulin** [Studio3T/robomongo#1557]
Like code indent? 

Default, the code indent of the shell script is 4. I want to the code indent is 2.

And there is bracket left align issue.

```js
db.posts.update({_id: ObjectId('5b3b1a6633558083e0c5c8fc')}, {
    $push: {
        $each: {
         // when I type enter here, as you can see, the bracket is not left align.
            }
    }
});
```

Robo 3T 1.2.1

**Comment by simsekgokhan** [comment]
Hi @mrdulin, sorry for answering so late, there is no such setting currently.
