### ISSUE TITLE
Not able to connect with replica set and direct connection is established

### ISSUE THREAD

**Issue by shree007** [Studio3T/robomongo#1562]
Hello,

I have installed studio 3t community version and try to connect to a replica set but it doesn't work.

I create separated Connection with the 3 members (Direct Connection without SSH or SSL) and I can connect to each members with no troubles.

But when I create the Connection for the replica set including the same 3 members, I always have the error message:

"Cannot connect to replica set...
Set's primary is unreachable.
Reason:
No member of the set is reachable."
Replica set name is rs0 .
Thanks for your help.

**Comment by helpermethod** [comment]
Same problem here. This is a real blocker for me.

**Comment by xGanimeDx** [comment]
Hello @shree007, if the problem related to Studio 3T better to contact https://studio3t.com/feedback/ since this repo related only to Robo 3T project
