### ISSUE TITLE
Failed to execute "listdatabases" command

### ISSUE THREAD

**Issue by watoua** [Studio3T/robomongo#1566]
HI, I got an error when used  robo3T(1.2) to connect mongodb(3.4.1) on window 7: 
failed to load list of databases, and the error detail is "Failed to execute "listdatabases" command. ".
But access control is not enabled for my mongo server.  How can i solve this problem? 
Here is the mongodb server log:
[thread1] connection accepted from 127.0.0.1:63516 #3487 (28 connections now open)
[conn3487] received client metadata from 127.0.0.1:63516 conn3487: { application: { name: "robo3t" }, driver: { name: "MongoDB Internal Client", version: "3.4.3-10-g865d2fb" }, os: { type: "Windows", name: "Microsoft Windows 7", architecture: "x86_64", version: "6.1 SP1 (build 7601)" } }
[conn3487] command admin.$cmd appName: "robo3t" command: listDatabases { listDatabases: 1, nameOnly: true } numYields:0 reslen:18812 locks:{ Global: { acquireCount: { r: 448 } }, Database: { acquireCount: { r: 223 } } } protocol:op_command 12014ms
[conn3487] end connection 127.0.0.1:63516 (28 connections now open)

**Comment by GCSBOSS** [comment]
Same happening here. Possibly something wrong with our data folder. Can anyone help?

**Comment by simsekgokhan** [comment]
Hi @watoua, @GCSBOSS and all, thanks for reporting the problem. 
Can you share the followings for further investigation please? 
- Robo connection config. details (screenshots)
- Robo logs (see left-bottom of main window)
- Output of listDatabases command with mongo
```
// Example for Windows 
E:\>mongo
MongoDB shell version v3.4.18
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.18
Welcome to the MongoDB shell.
> db.adminCommand( { listDatabases: 1 } )
{
        "databases" : [
...
}
```

Meantime, I suggest the following actions: 
- Restart the mongodb server 
- Try with MongoDB v3.4.18 (official latest 3.4 version)

**Comment by xplorer1** [comment]
Hello. You need to go to Manage Connections > Edit > Authentication. Fill in the details there. That should work like magic.

**Comment by simsekgokhan** [comment]
We still need more details for further investigation. 

Meantime, you can try the beta. Feel free to open the ticket if you find problem again.
Closing due to insufficient information about problem. 

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

**Comment by Qix-** [comment]
Can confirm, latest beta fixes this issue.

**Comment by simsekgokhan** [comment]
Thanks a lot for the feedback @Qix

**Comment by richarddd** [comment]
@simsekgokhan This is still an issue: Robo3t cant handle when there are zero databases on the server:

If i run this in the shell:

```rs0:PRIMARY> db.adminCommand( { listDatabases: 1 } )
{ "databases" : [ ], "totalSize" : 0, "ok" : 1 }````

Robo3t will result in: `Failed to execute "listdatabases" command`

Running version 1.3

**Comment by avimar** [comment]
I just had this issue with 1.2 connecting to a new mongo 4.2

It's fixed when using robo3t version 1.3, which supports newer version of mongo

**Comment by ShayNehmad** [comment]
Beta fixed it for me as well. Thanks!

**Comment by savanbthakkar** [comment]
I have Robo 3T 1.3.1. I still have this problem.

**Comment by maythamfahmi** [comment]
For me Have updated my Robo 3T version to 1.3.1 and hence I use it on local environment with out username and password, even after new installation, for some reason Perform authentication was enabled. I have to disable it. And it worked for me.
![image](https://user-images.githubusercontent.com/9260645/64613513-9eab4f80-d3d6-11e9-9533-4dc4b45900a0.png)

**Comment by savanbthakkar** [comment]
Worked for me now. The problem was: It can't connect if there are no databases to list. I had to create a database and a collection for it. Error message is misleading, but once you create a database and a collection, it works.

**Comment by jcezardasilva** [comment]
1.3.1 works for me.

**Comment by rossifedericoe** [comment]
I had the same problem with version 1.2.1, works with 1.3.1

**Comment by Susheer** [comment]
just install latest version  of 3t

**Comment by ChihHaoChen** [comment]
Same issue with 1.2 version, but 1.3.1 works on my side too.

**Comment by mikedehaan** [comment]
I'm receiving the same issue with the latest. 1.3.1

I can "Open Shell" and proceed as normal, but I cannot get the list of collections down the left-hand side to show up. I can run the command "show collections" and work manually with no problem.

![robo3t_about](https://user-images.githubusercontent.com/1839244/66972737-254cef80-f05b-11e9-9fa4-f1e04fb6efdd.jpg)
![robo3t_error](https://user-images.githubusercontent.com/1839244/66972738-254cef80-f05b-11e9-8550-ba7d6f2703b2.jpg)

**Comment by matheusalxds** [comment]
You'll need to use 1.3 version! :)

**Comment by Mert1980** [comment]
![Screenshot from 2019-12-31 22-45-33](https://user-images.githubusercontent.com/55088530/71635281-68af0700-2c23-11ea-9433-154652af1e97.png)
I am using the latest version but I can not connect to MongoDB at local host

**Comment by matheusalxds** [comment]
You'll need to upgrade mongodb to the last version, so you can to connect in your local database.

**Comment by Mert1980** [comment]
Actully I am using the latest version and I managed to connect to database after filling in the authentication field while creating a new connection. I had no issue yesterday but today I receive the error which can be seen on the picture. I could not figure out the reason???
![Screenshot from 2020-01-03 09-49-37](https://user-images.githubusercontent.com/55088530/71714481-60ff8600-2e0e-11ea-9017-46dc23e81910.png)

**Comment by lisaiceland** [comment]
Just downloaded the latest 1.3.1 and ran it. It's working fine now.

**Comment by Mert1980** [comment]
Thank you very much for the information.

14 Şub 2020 Cum, saat 02:15 tarihinde Lisaiceland <notifications@github.com>
şunu yazdı:

**Comment by donqhomo** [comment]
> We still need more details for further investigation.
> 
> Meantime, you can try the beta. Feel free to open the ticket if you find problem again.
> Closing due to insufficient information about problem.
> 
> Robo 3T 1.3 Beta
> https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

I just updated robo3t from version 1.2 to version 1.3 and it worked with mongodb new version (4+)

**Comment by babul101** [comment]
I was also facing the same issue.
So i updated my robo3t from 1.2 to 1.3 with the latest mongodb version.
And it is working perfectly now

**Comment by sunnyatticsoftware** [comment]
It seems there were two issues here. I tried with the latest 1.3.1 and had the issue. As soon as I created a DB through Azure Cosmos DB portal, it worked.

**Comment by phil-warner** [comment]
<img width="453" alt="Screenshot 2020-09-04 at 15 26 25" src="https://user-images.githubusercontent.com/11527616/92250285-2d0bc180-eec3-11ea-8a14-b75733d85adb.png">

Just upgraded to Robo 3T for Mac 1.4 and now getting this.

**Comment by ledulla** [comment]
Because you need to add authentication and enable the checkbox for manually specify visible databases
