### ISSUE TITLE
'Repair Database' in Robo3T needs a confirm dialog box!

### ISSUE THREAD

**Issue by gloomyrose** [Studio3T/robomongo#1568]
Robo 3T version : 1.2.1

Hello, My name is Myung-jin Choi, the programmer using MongoDB.

A few minutes ago, I was using Robo3T, and I misclicked 'Repair Database' on the DB which I didn't intend to click. And the DB is still hanged.(It's running on production service.)
I think a confirm dialog box is really necessary for 'Repair Database' menu to avoid this kind of problem. Would you add this feature in the next version?

Thank you in advance.

![repairdatabase](https://user-images.githubusercontent.com/25146973/43623989-84b05494-971f-11e8-923b-8ad002af579e.png)

**Comment by simsekgokhan** [comment]
You check the beta. Feel free to open the ticket if you find problem again.

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta
