### ISSUE TITLE
Please add support for SCRAM-SHA-256 auth

### ISSUE THREAD

**Issue by pvermeil** [Studio3T/robomongo#1569]
Hello Robot3T team. Since Mongo 4 release default auth mechanism when auth is enabled is SCRAM-SHA-256. Do you plan to support it in a near future ? Otherwise all MongoDB newcomers have to change this.
Thanks, have a nice day

**Comment by markvankempen** [comment]
Pretty please?

**Comment by q16458** [comment]
Hello Robo3T team, do you have plan to support this? That's really important for Mongo 4 users, otherwise I only can change to other tool. Thanks.

**Comment by markvankempen** [comment]
Pretty please with a cherry on top?

**Comment by simsekgokhan** [comment]
Hi @pvermeil and all, thanks for the request. 
We are including support for SCRAM-SHA-256 auth mechanism in the next release Robo 1.3 along with MongoDB 4.0 support.

**Comment by q16458** [comment]
That's really a good news at the end of 2018! Expect to get the release 1.3 as early as possible. Thanks for your effort.

**Comment by markvankempen** [comment]
Any ball park ETA on v1.3?

**Comment by simsekgokhan** [comment]
Hi All, thanks for reporting this. Can you please try our beta? Hopefully it will work.

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

@markvankempen I am hoping in a couple of weeks.

**Comment by simsekgokhan** [comment]
Beta with SCRAM-SHA-256 support has been updated with more changes:

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

**Comment by DaveWelling** [comment]
Thank you! I was able to login with SCRAM-SHA-256.  If you are interested, it did not work with an existing connection entry that I changed to be 256 -- I had to create a new connection entry pointed at the same user and then it worked.  For existing connection entry received: U_STRINGPREP_PROHIBITED_ERROR.  Hope that helps.
