### ISSUE TITLE
Can not connect to replica set with secured connection without certifcates

### ISSUE THREAD

**Issue by vzaytsev** [Studio3T/robomongo#1571]
I've got a connection string like this, which perfectly works with mongodb shell

mongodb://user:password@server1:27017,server2:27017,server2:27017/DBNAME?replicaSet=RSNAME&ssl=true&authSource=someSource

When i try to connect from Robomongo, any usage of ssl requires authentication method and certificates, but mongodb shell is not, just use ssl protocol.

**Comment by rnd49** [comment]
Yo can use it as workaround
___
![image](https://user-images.githubusercontent.com/26868471/46231076-41f48780-c373-11e8-91aa-f37f3045ccde.png)
___
if it not help, try identify which cert exactly used:
`openssl s_client -showcerts -connect one-of-your-rs-hosts:27017`

example response:
```
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
```

**Comment by simsekgokhan** [comment]
Hi @vzaytsev , thanks for reporting the problem. 
At first glance, I expect that "Self-signed Certificate" should work. Have you tried that option? 
If so, can you share the followings please? We need it for further investigation.
- Connection error window screenshot
- Screenshots of connection settings 
- Robo logs (see it on the left-bottom of main window)

**Comment by simsekgokhan** [comment]
@vzaytsev 
You can also try new beta: 
Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta
