### ISSUE TITLE
Connection failed.  SERVER [] (Type: UNKNOWN)  |_/ Connection error (MongoSocketWriteException): Exception sending message |____/ Socket error: Connection reset

### ISSUE THREAD

**Issue by guawazi-glitch** [Studio3T/robomongo#1574]
Hi guys, my studio 3T failed when connecting to mongodb within following errors:
'''
Connection failed.

SERVER [] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketWriteException): Exception sending message
|____/ Socket error: Connection reset

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {java.net.SocketException: Connection reset}}]
'''

I'm new to mongodb so how could I start my debug? I can't find any logs.
BTW, I running my mongodb inside my docker.

**Comment by simsekgokhan** [comment]
Hi @guawazi-glitch , this is Robo 3T support. Please contact Studio 3T.
