### ISSUE TITLE
Failed to refresh 'Collections' of mongo 2.7.8

### ISSUE THREAD

**Issue by ninja0828** [Studio3T/robomongo#1576]
# scenario
Could connect to mongo, but Failed to refresh 'Collections' of mongo 2.7.8.
![image](https://user-images.githubusercontent.com/39983039/45008726-d1d63880-b036-11e8-9a48-4bc9a75682af.png)

# version
![robo](https://user-images.githubusercontent.com/39983039/45008712-c2ef8600-b036-11e8-8257-a5dc23b103d1.png)
![macOS](https://user-images.githubusercontent.com/39983039/45008791-1c57b500-b037-11e8-8d2e-b533a7aefa9e.png)
![mongo](https://user-images.githubusercontent.com/39983039/45008743-e5819f00-b036-11e8-8526-50072033915f.png)

**Comment by simsekgokhan** [comment]
Hi @ninja0828 , thanks for reporting the problem and sorry for answering so late.
Do you still have the problem? Can you try with other versions? https://github.com/Studio3T/robomongo/releases
