### ISSUE TITLE
Crash on linux x64

### ISSUE THREAD

**Issue by ashep** [Studio3T/robomongo#1578]
Downloaded and installed latest version from website. After staring have following messages in console output:
```
free(): invalid pointer
Aborted (core dumped)
```

Where can I see logs or something else to figure out why it crashes. Thank you.

**Comment by xGanimeDx** [comment]
Hello @ashep, you can use Robo 3T under Linux without installation. Just unarchive .tar.gz using: 
`tar -xzf archive.tar.gz`
and then run robo3t file from bin directory:
`./robo3t`
