### ISSUE TITLE
The copied content contains illegal characters

### ISSUE THREAD

**Issue by xf8** [Studio3T/robomongo#1580]
I automatically included illegal characters when I copied the fields.  The version number is Robo 3T 1.2.1
![image](https://user-images.githubusercontent.com/5242314/45219382-4d591380-b2dd-11e8-95a6-42afb12adb81.png)

**Comment by simsekgokhan** [comment]
Hi @xf8 , thanks for reporting the problem and sorry for answering so late. 
Can you share the original value that you are copying? We are not sure how to reproduce the problem.

**Comment by xf8** [comment]
This bug may have been fixed in version 1.3.1, but I did not find this problem in this version.thanks.
