### ISSUE TITLE
MacOS robo3t app crashes after I open up the edit window

### ISSUE THREAD

**Issue by sakalys** [Studio3T/robomongo#1581]
Robo 3T 1.2.1
MacOS

A window with results (big collection) from a regex (unindexed) search was open. The crash happens after one enters the edit window of a document from that result set.

By the way, the results are displayed from a remote server which is accessed over an SSH tunnel.

**Comment by sakalys** [comment]
Correction:
I think the crash happens after I hit Save (Or any other crud operation) which triggers a result set refresh.

So to recap:
1. load a slow result-set;
2. Edit/delete a document for the set;
3. During the loading (there is no indication for that), try to open up another document for editing.

**Comment by simsekgokhan** [comment]
Hi @sakalys , thanks for reporting the problem. 
Can you please try our beta? We cannot reproduce your problem but we have some related code changes which can fix your problem. 

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

**Comment by sakalys** [comment]
Still reproducable in beta

**Comment by sakalys** [comment]
I'll upload a video shortly

**Comment by sakalys** [comment]
https://www.youtube.com/watch?v=MvXOrHZdIM8

**Comment by gsimsekfb** [comment]
@sakalys Thanks a lot for the video, the problem is clear now. At first glance, seems like we need to disable editing and show progress bar while waiting for a doc edit operation to be finished.

**Comment by simsekgokhan** [comment]
@sakalys Thanks a lot for the video, the problem is clear now. At first glance, seems like we need to disable editing and show progress bar while waiting for a doc edit operation to be finished.

**Comment by simsekgokhan** [comment]
@sakalys We have entered some changes, can you check please? 
Feel free to open the ticket if you find problem again.

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

**Comment by sakalys** [comment]
Well, if you tested it, it ought to work, right? :)

**Comment by sakalys** [comment]
I can confirm, that the issue in topic has been fixed.

**Comment by simsekgokhan** [comment]
@sakalys 
Cool, thanks a lot for verifying. We tested but you never know, crashes are always hard problems ;)
