### ISSUE TITLE
Robo 3T log file location Windows

### ISSUE THREAD

**Issue by Valijon** [Studio3T/robomongo#1587]
It's suppose to create log file in %TMP% o %TEMP% path, but no log file is found.

StackOverflow: https://stackoverflow.com/questions/52363718/robo-3t-log-file-location-windows

Robo 3T version: 1.2.1
OS: Windows 8.1

**Comment by simsekgokhan** [comment]
Hi @Valijon , thanks for reporting the problem and sorry for answering so late.
The link does not work. Can you explain the problem please?
