### ISSUE TITLE
Feature: Support DNS SRV based MongoDB connections

### ISSUE THREAD

**Issue by mohag** [Studio3T/robomongo#1588]
[Mongo supports SRV-record based connections](https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format). It would be nice if Robo 3T supported them.

A basic level of support could be to pre-fill a connection configuration based on the SRV records. (This would need a manual edit if the DNS entries change)
Full support would be to look up the entry every time the connection is made (or letting the client library deal with it)

**Comment by simsekgokhan** [comment]
@mohag Thanks a lot for the suggestion. 
We have already started to develop basic level of support for this feature. 

By basic level of support do you mean importing (or parsing) connection setting details from SRV connection string? (set members, set name, username, password etc ..)

Robo will then pass the connection details to MongoDB drivers to connect. So it feels like correctly parsing and passing these parameters will be what Robo can do here.

This screenshot is a very early version of development: 
<img src="https://user-images.githubusercontent.com/19390749/53643286-bd20d900-3c44-11e9-8abf-9a50ff9618c4.jpg" width="500" />

**Comment by mohag** [comment]
That looks good, thanks!

Correct, with basic support I meant that if the relevant client library doesn't to support it or the connection string generation needs too much work, pulling that info in might be easier than full support.  (A proper connection string also seems to clash with the separate auth tab - if both is filled in, which one gets used?) (i.e. Basic support - just in the GUI to configure it - filling in existing fields, full support - in the logic when a connection takes place)

**Comment by Elyx0** [comment]
Is this live for Studio3T mac? I couldn't import a +srv connection string

**Comment by mewelling** [comment]
> Is this live for Studio3T mac? I couldn't import a +srv connection string

I just downloaded robo3T v1.3.1 for mac and it looks like it does indeed support SRV records 👍

**Comment by abheeksambyal1725** [comment]
not able to use "From SRV" for providing the string
![image](https://user-images.githubusercontent.com/33353231/149633282-6c714167-6f75-496d-a0d3-d7eef73910da.png)

**Comment by mohag** [comment]
> not able to use "From SRV" for providing the string (using Robo 3t-1.4 on windows). Where do i set the option to use srv? !
"From URI"
