### ISSUE TITLE
High ram usage on windows

### ISSUE THREAD

**Issue by Transisto** [Studio3T/robomongo#1592]
![image](https://user-images.githubusercontent.com/388716/47679739-5955a900-db9b-11e8-8564-d3f7d7d67d97.png)

The DB I've opened was very small and closing connection to all database doesn't lower ram usage one bit.

**Comment by Transisto** [comment]
Actually a few second after opening the app and without having done anything the RAM usage is ridiculous.

![image](https://user-images.githubusercontent.com/388716/47680599-a470bb80-db9d-11e8-869e-d459401fd2aa.png)

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/49674258-5aea7a80-fa3f-11e8-83dc-2d5490893110.png)

Ridiculous

**Comment by Transisto** [comment]
nothing has improved with last version

**Comment by simsekgokhan** [comment]
Hi @Transisto, thanks for reporting the problem. This is the support page for Robo 3T. 

For Studio 3T problems please see:
https://studio3t.com/feedback/
