### ISSUE TITLE
App keep Crashing while Editing Documents

### ISSUE THREAD

**Issue by UsamaAmjad** [Studio3T/robomongo#1593]
I am facing frequent crashes while editing/updating documents via given dialog box. I am using macOS High Sierra. Please review the attached crash report for further crash details.

[crashReport.txt](https://github.com/Studio3T/robomongo/files/2554133/crashReport.txt)

**Comment by simsekgokhan** [comment]
Hi @UsamaAmjad, thanks for reporting the problem. 

Can you tell use the steps to recreate this issue and exactly at which step it crashes?
Also, we have some changes to fix some crashes. Can you try the beta? Fingers crossed. 

[Robo 3T 1.3 Beta](https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta)

**Comment by UsamaAmjad** [comment]
Its been a while since I used it, don't remember exactly. Will try again and report.
