### ISSUE TITLE
Can't get more than 50 records

### ISSUE THREAD

**Issue by elias6** [Studio3T/robomongo#1595]
I am trying to do a query in Robo 3T. I want to see all of the records. I entered 99999 in the batch size input (since that number is much bigger than the number of records) and pressed command+enter and it seems to bring them up. But as soon as I move my mouse, it changes back to 50 and only shows 50 records. This is annoying. Is there any way to make it not do this?

I am using Robo 3T 1.2.1 on OS X 10.13.6. What I am trying to do has worked for months and just stopped working this morning.

**Comment by elias6** [comment]
I tried restarting Robo 3T and it still happened. I restarted my laptop and it is still happening.

If I don't move my mouse, the batch size seems to change to 50 on its own about a second after running the query.

**Comment by elias6** [comment]
I noticed something. If I type 9999 and press command+enter (which I’m in the habit of doing, since that runs the query from the text box), it runs the query and resets to 50. But if I type 9999 and press enter, it shows all the records. This is weird and confusing but I guess I can get used to it.

**Comment by jeanceppi** [comment]
Hi, same problem here, except even if I put any number greater than 50 in the "Batch Size" field and press Enter, nothing happens. It works well for numbers smaller or equal to 50, but not greater.

I am using Robo 3T 1.2.1 on Ubuntu 18.04.1 (4.15.0-38 x86_64)

**Comment by simsekgokhan** [comment]
Hi guys, will changing `"batchSize" : 50,` in Robo config file be helpful?

```
Important: Make a copy of config file before editing it.
Close Robo 3T
Change "batchSize" in config file and save file. 
Open Robo 3T 
```

See:
https://github.com/Studio3T/robomongo/wiki/Robomongo-Config-File-Guide

@jeanceppi 
Ubuntu 18.04 is supported only from Robo 1.3. Please try the Robo 1.3 Beta:
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

**Comment by elias6** [comment]
I am running Robo 3T 1.2.1 on macOS High Sierra version 10.13.6. I edited my `~/.3T/robo-3t/1.2.1/robo3t.json` file and changed the `batchSize` setting to 1000. Now I can get more than 50 records without having to change the setting manually every time I run a query.
