### ISSUE TITLE
Pagination in Robo3T fails when DOT Operator is used while filtering data using $match

### ISSUE THREAD

**Issue by preshudigit** [Studio3T/robomongo#1604]
As you all know by default 50 documents will be displayed as part of results. But i'm unable to view next page if i use the DOT Operator in query having $match condition, which eventually shows the below error.

Error: Line 1: Unexpected token .

I got to know from some people that this can be bug on Robo3T.

**Comment by simsekgokhan** [comment]
Hi @preshudigit , thanks for reporting the problem. 
We have some changes to fix this problem. Can you try the beta? Fingers crossed. 

[Robo 3T 1.3 Beta](https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta)
