### ISSUE TITLE
characters in JSON Document is overlapping in view document window (RoboMongo)

### ISSUE THREAD

**Issue by lahirusamith** [Studio3T/robomongo#1613]
when you are trying to view documents in RoboMongo, the characters of json content is overlapping. this is only happened when trying to open view document window on an extended display.
![capture](https://user-images.githubusercontent.com/5174183/53224034-4d857980-3699-11e9-88ec-ee7b8b0af320.PNG)
![capture2](https://user-images.githubusercontent.com/5174183/53224036-4d857980-3699-11e9-8ff5-76a3970f051d.PNG)

**Comment by simsekgokhan** [comment]
Hi @lahirusamith , thanks for reporting the problem and sorry for answering so late.
Can you please share the followings for further investigation? 
- Robo 3T version
- OS version

**Comment by simsekgokhan** [comment]
Hi, on Windows & macOS, we have upgraded our Qt version to 5.12.8 (Apr/2020).
I hope Robo 3T 1.4 will fix some of your problems -> [Robo 3T 1.4](https://github.com/Studio3T/robomongo/releases/tag/v1.4.0)
