### ISSUE TITLE
Can't retry after timeout is reached 1.3.1

### ISSUE THREAD

**Issue by DaavisGit** [Studio3T/robomongo#1628]
Hello. 
I'm using Robo 3T 1.3.1 on Ubuntu 18.04.2 LTS and encountered a very annoying problem.

Once I reach timeout on any query that query tab is broken and I can't retry anymore. 
The error I'm getting is:
`Failed to execute script. Error: Invalid parameter: expected an object ()`
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/11573591/55533777-0f796d80-56bb-11e9-9596-654b0c29bbe8.png)

I have tried various different queries and this can happen to any of them once they reach timeout. 

This problem didn't occur on 1.2.1

Hoping on a resolution, Thank you!

**Comment by freefish1218** [comment]
same problem  + 1

Hoping on a resolution, Thank you!

**Comment by jskrzypek** [comment]
Ahah! Thank you!! I thought I was losing my mind 😖

**Comment by smpco** [comment]
+1 Same problem on Robo 3T 1.3.1 on macOS Mojave 10.14.2. A quick restart of the app makes the error go away.

**Comment by AugustoTorres-Reflektion** [comment]
+1 Same problem on Robo 3T 1.3.1 
System:
`ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226`

**Comment by laiseng** [comment]
the tab session is disconnected from database
try to add the `use [dbName]` before executing script 
```
use [dbName]
[Your Script Here]
```

**Comment by goluzdravi-penzioner** [comment]
+1 Same problem on Robo 3T 1.3.1 on macOS Catalina 10.15.3

**Comment by davidhmgs** [comment]
Same issue here!

**Comment by ollydixon** [comment]
Also facing this issue, can't find the 1.2 version for download on Mac, is there no testing with this product?

**Comment by EXPEKgoel** [comment]
I am too facing the same issue with Robo 3T 1.3.1

**Comment by arjungupta0107** [comment]
Facing the same issue

**Comment by AlexanderTunick** [comment]
the same issue, already flipping me out, tired to rebook the app...
`MacBook Pro (15-inch, 2019)`

**Comment by prebm** [comment]
A workaround that worked for me was duplicating the query in a new tab. Via right click on the tab or Shift+Cmd+T on Mac.

**Comment by paul-maxime** [comment]
Same issue, I was wondering why I couldn't get any query to work.
Opening a new tab works fine.

**Comment by simsekgokhan** [comment]
Hi , we have some fixes related to this problem.
I hope Robo 3T 1.4 will fix some of your problems -> [Robo 3T 1.4](https://github.com/Studio3T/robomongo/releases/tag/v1.4.0) 
Please let us know.

**Comment by DaavisGit** [comment]
I can confirm that it works in 1.4
Thanks!
