### ISSUE TITLE
Does Robo 3T cache data anywhere on the user's computer? Is it safe for sensitive data?

### ISSUE THREAD

**Issue by riverfr0zen** [Studio3T/robomongo#1646]
Considering use of Robo 3T so some business users can view databases containing sensitive information that should not be stored on their machines. My question is whether Robo 3T caches data from queries (or other) for performance purposes, and if so, where is that cache located (e.g. registry, filesystem, or other)?

Note, I'm not asking about data that is exported or saved manually by the user, but any data that is stored on the user's machine by Robo 3T for its internal purposes.

Thanks in advance.

**Comment by icodeface** [comment]
look for the same answer

**Comment by simsekgokhan** [comment]
Hi @riverfr0zen , @icodeface , one of the maintainers here. This is the cache location: https://github.com/Studio3T/robomongo/wiki/Robomongo-Config-File-Guide. Only Robo config file and some cache files for Welcome tab.

**Comment by riverfr0zen** [comment]
Thanks @simsekgokhan. Closing this now.
