### ISSUE TITLE
Robo3t not starting up.

### ISSUE THREAD

**Issue by usama-asfar** [Studio3T/robomongo#1655]
Suddenly robo3t doesn't start, can't understand what's gone wrong. I'm using Ubuntu 18.04.2 LTS

Error
```
usama@usama:~$ robo3t-snap
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

```

**Comment by jtognazzi** [comment]
I have a similar problem on Fedora 30, as a workaround you can try to start it with wayland disabled:
`DISABLE_WAYLAND=1 robo3t-snap`

**Comment by viniciusgati** [comment]
same here, workaround works.

**Comment by talhag3** [comment]
@jtognazzi where i can add ```DISABLE_WAYLAND=1 robo3t-snap```

**Comment by viniciusgati** [comment]
have you tried on the terminal this exact command? i think it will work,

then you can create a path variable to on the OS.

Att.

Em qua., 20 de jan. de 2021 às 05:20, MUHAMMAD TALHA <
notifications@github.com> escreveu:

**Comment by Pemidi** [comment]
> I have a similar problem on Fedora 30, as a workaround you can try to start it with wayland disabled:
> `DISABLE_WAYLAND=1 robo3t-snap`

that works, thank you @talhag3

**Comment by mirao** [comment]
> `DISABLE_WAYLAND=1  robo3t-snap`

Does it mean that Robo3T doesn't have native support for Wayland?

**Comment by visakhvjn** [comment]
`DISABLE_WAYLAND=1` worked. Thanks

**Comment by Hypnocrit** [comment]
This is not a proper solution.  Do we have a better one?

**Comment by mirao** [comment]
Now I'm running Ubuntu 22.10, Gnome 43.1 (Wayland), Robo 3T 1.4.4 (Build e6ac9ec - 1/2023).

Interestingly if I start Robo3T over launcher (`robo3t.desktop`), it works fine.
This is the launcher content.
```
[Desktop Entry]
Name=Robo3t
Comment=Robo 3T (formerly Robomongo) is the free lightweight GUI for MongoDB enthusiasts.
Exec=robo3t-snap
Terminal=false
Type=Application
Icon=${SNAP}/meta/gui/icon.png
Categories=GNOME;GTK;Network;Utility
StartupWMClass=robo3t
```
But if I start it from command line using `robo3t-snap`, it fails. I have to start it over `DISABLE_WAYLAND=1 robo3t-snap`

**Comment by EmilSkjetne** [comment]
Im running ubuntu 22.04 and got it to work by editing the .desktop file

Path: `/var/lib/snapd/desktop/applications/robo3t-snap_robo3t.desktop`
```
[Desktop Entry]
X-SnapInstanceName=robo3t-snap
Name=Robo3t
Comment=Robo 3T (formerly Robomongo) is the free lightweight GUI for MongoDB enthusiasts.
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/robo3t-snap_robo3t.desktop env DISABLE_WAYLAND=1 /snap/bin/robo3t-snap
Terminal=false
Type=Application
Icon=/snap/robo3t-snap/9/meta/gui/icon.png
Categories=GNOME;GTK;Network;Utility
StartupWMClass=robo3t
```
Note the `env DISABLE_WAYLAND=1` on line 5

For me it starts just fine after that.

Now if you update the application this might be overwritten tho...
But don't fix what ain't broken
