### ISSUE TITLE
Document Editor - Cursor alignment issue

### ISSUE THREAD

**Issue by masterjaso** [Studio3T/robomongo#1663]
When using the 'edit document' or 'insert document' feature, the text editor that opens has text and cursor alignment issues.
![Robo3t_TextIssue](https://user-images.githubusercontent.com/7506680/62131917-1f404180-b2aa-11e9-9901-d799432bbfb5.PNG)

The cursor in the attached image is actually at the end of the line.  Also notice the commas are tucked under the text.  Makes it very difficult to modify items in the editor.

**Comment by mozhgan8** [comment]
I have the same issue!

**Comment by LawrenceRao007** [comment]
Same here.  I have to paste document into an external editor then paste back with the changes.

**Comment by simsekgokhan** [comment]
Hi @masterjaso , all, thanks for reporting the problem and sorry answering so late. 
We did not see this during development or QA. 

Can you please help us how to reproduce and share the followings for further investigation? 
- Robo 3T version
- OS details (Win 7, Ubuntu 18.04 etc..)

**Comment by simsekgokhan** [comment]
Hi, on Windows & macOS, we have upgraded our Qt version to 5.12.8 (Apr/2020).
I hope Robo 3T 1.4 will fix some of your problems -> [Robo 3T 1.4](https://github.com/Studio3T/robomongo/releases/tag/v1.4.0)

**Comment by rupaliagarwal** [comment]
I have Robo 3T 1.4 but still facing the same issue.

**Comment by matthewfrost-360** [comment]
Still happening on 1.4.4 for me, Windows 10 Pro Build 19042. Tried re-installing and removing files from Program Files, appdata and the user directory
