### ISSUE TITLE
Unable to See Collections

### ISSUE THREAD

**Issue by derekrprice** [Studio3T/robomongo#1666]
Connecting to Azure's Cosmos DB with Studio3T for MongoDB 2019.4.1, I am unable to see any existing collections.  When I create collections using the Studio3T UI, I am briefly able to see them, but they eventually disappear (I may have disconnected and reopened the connection).  Importing data to an existing collection works, despite it not being visible in the UI - I can view the created collections and the imported data in the Azure portal, but it is still not visible in the Studio3T UI.

**Comment by uda** [comment]
I think this has since been solved, not sure which side, but it does work for me as expected.

**Comment by derekrprice** [comment]
I no longer care, as we have abandoned CosmoDB for other reasons.  I'm closing this.
