### ISSUE TITLE
Unable to connect to MongoDB v4.2

### ISSUE THREAD

**Issue by FROGGS** [Studio3T/robomongo#1667]
I get the following error:

```
Cannot connect to the MongoDB at <my ip here>.

Error:
Network error while attempting to run command 'saslStart' on host '<my ip here>'
```

I have four servers under my control, and I can connect to two of them running v3.6 and v4.0, and cannot connect to the other two running v4.2.

Sadly I was unable to spot anything obvious in the mongodb release notes at https://docs.mongodb.com/manual/release-notes/4.2/

**Comment by zhe1ka** [comment]
the same issue. on 3.6, 4.0 works as expected but on 4.2 i have the same error. I use ssh connection

![image](https://user-images.githubusercontent.com/6460571/63635890-afd32d00-c670-11e9-89d2-cc5326cb7b81.png)

I remember some time ago there was the same problem with previous versions of mongodb and it was fixed.

**Comment by zhe1ka** [comment]
found one possible solution:
https://github.com/Studio3T/robomongo/issues/1590#issuecomment-475954939

but i can't regen my ssh so if someone tries it please let me know

**Comment by jeyarajcs** [comment]
I also faced the same issue.
Download and install latest version of Robo 3T will solve this problem..

**Comment by zhe1ka** [comment]
It works, thanks) weird, that it's not updated automatically, at least some time I have a notification that it can be updated. nevertheless the problem is solved

**Comment by FROGGS** [comment]
Same for me, I somehow managed to not check the version number before raising this issue.
I've updated to the latest version and all works fine.

**Comment by Runa-Redapple** [comment]
Thanks its working fine
