### ISSUE TITLE
Robo 3T crash after Windows 10 update to Version 10.0.17763 Build 17763

### ISSUE THREAD

**Issue by lincoln42** [Studio3T/robomongo#1687]
After the update the program fails to start up at all and the error below is logged in the Windows Event Log.

Does anyone know how to fix this issue? 

If any Robo 3T engineers are reading this please help me fix this problem.

```
Faulting application name: robo3t.exe, version: 1.3.1.0, time stamp: 0x5c948f3a
Faulting module name: ISD_Tablet.dll, version: 7.3.4.35, time stamp: 0x5a274039
Exception code: 0xc0000094
Fault offset: 0x00000000000d6200
Faulting process id: 0xa238
Faulting application start time: 0x01d5790bf0eba8ea
Faulting application path: C:\Program Files\Robo 3T 1.3.1\robo3t.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ISD_Tablet.dll
Report Id: ea5e26af-31c5-4e85-9e87-321a4ea6c2af
Faulting package full name: 
```

**Comment by simsekgokhan** [comment]
Hi @lincoln42 , sorry for the delay and thanks for reporting the problem. Did you start to see this problem with Robo 1.3? No crash with Robo 1.2? And can you share all of the event log please?

So the crash is coming from system file `ISD_Tablet.dll`. What you can research if it is possible to - without giving harm to your system - update drivers related to that dll or to disable the "Wacom ISD Service" in Services.
