### ISSUE TITLE
Paging broken in DocumentDB 

### ISSUE THREAD

**Issue by swordfish444** [Studio3T/robomongo#1694]
# Description
When paging between queried results or trying to increase the page size fails with an error.

## Expected results
Increasing the page size shows that number of documents. Navigating between pages shows that page of data.

## Actual results
Increasing page size fails and returns error `Unrecognized field: 'ntoreturn'`. Navigating between pages fails and returns error `Unrecognized field: 'ntoreturn'`. 

![image](https://user-images.githubusercontent.com/3893966/69918070-6427e080-1422-11ea-95b3-a158c067d78d.png)

## Notes
- DocumentDB cluster running engine **docdb 3.6.0**
- Connecting to Primary cluster endpoint
- SSL enabled
- SSH tunneling (ssh -> jumpbox -> documentdb)

**Comment by Steffan-Carlos** [comment]
+1

**Comment by mfranci29** [comment]
+1

**Comment by gobozov** [comment]
+1

**Comment by phyrian** [comment]
+1

**Comment by himanshu-nx** [comment]
I'm facing similar issue. Any update on this?

**Comment by caseymdk** [comment]
Experiencing same issue. This seems pretty breaking no?

**Comment by simsekgokhan** [comment]
Hi @swordfish444, all, thanks for reporting the problem. We are working to fix this problem. The beta 1.4.2 is ready.

Could you guys give it a try and tell us if it solves the page navigation and page size problems?
Download -> [Robo 1.4.2](https://github.com/Studio3T/robomongo/releases/tag/v1.4.2)

**Comment by xiic** [comment]
Thank you, this fixed the issue for me.

**Comment by Steffan-Carlos** [comment]
Fixed for me as well

**Comment by kathrynvargas** [comment]
Robo 3T 1.4.2 is now generally available for download: https://robomongo.org/download/

**Comment by mariuszjedrzejewski** [comment]
Does 1.4.2 update fixes also my issue: https://github.com/Studio3T/robomongo/issues/1760?
