### ISSUE TITLE
Authentication Database option isn't used properly

### ISSUE THREAD

**Issue by bbuivn** [Studio3T/robomongo#1696]
Hi,

Here's my environment:
```
Robot 3T 1.3.1
MacOS 10.15.1

5 Nodes Replicaset
MongoDB 3.6.13

SSL is configured with a private CA
```

### What am I trying to do?
I'm trying to connect directly to a Secondary node of the replicaset - using `Direct Connection` - to a database and authenticating on another one.

This does work like a charm with mongodb cli, as expected with the `authSource`/`--authenticationDatabase` parameters.
But it doesn't when I use Robot 3T.

### What happens?
I've setup a standalone MongoDB with authentication enabled, an authentication database `authdb` and two other databases: `mydb` and `otherdb`.
I've setup a user named `benoit.bui` with the following accesses:
```
"roles" : [ 
    { "role" : "read", "db" : "mydb" }, 
    { "role" : "read", "db" : "otherdb" } ]
```
Here's captures of my configuration
<img width="772" alt="image" src="https://user-images.githubusercontent.com/561357/72166751-1f507b80-33ca-11ea-906f-641eb6ecd106.png">
<img width="772" alt="image" src="https://user-images.githubusercontent.com/561357/72166765-24adc600-33ca-11ea-90bc-a90d6df31a54.png">
<img width="772" alt="image" src="https://user-images.githubusercontent.com/561357/72166807-37c09600-33ca-11ea-97a3-561fa4e80bf2.png">

With this configuration, authentication and connection does work but I end up on the `authdb` database, not `mydb` as specified on the `Default Database` setting in the `Advanced` toggle.

This does work with Studio 3T
<img width="633" alt="image" src="https://user-images.githubusercontent.com/561357/72166885-663e7100-33ca-11ea-94b1-273424ac1e6b.png">

This results to a scan of accessible databases:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/561357/72166939-79514100-33ca-11ea-90da-0954220d0be8.png">

I do have the same behaviour with MongoDB Compass, it scans accessible databases
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/561357/72167117-d0efac80-33ca-11ea-8049-bf511aba6c26.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/561357/72167400-5d9a6a80-33cb-11ea-9de9-f4a7c1ed79ad.png">

Am I missing something or did I misconfigure Robot 3T?

Thanks!

**Comment by bbuivn** [comment]
Any input on this, please?

**Comment by simsekgokhan** [comment]
Hi, thanks a lot for reporting the problem with details. We will investigate.

The only part that is not clear is the result in Robo 3T. Which dbs can you access with Robo 3T? Maybe you can attach a screenshot of accessible databases, like you did with Studio 3T?

**Comment by bbuivn** [comment]
> The only part that is not clear is the result in Robo 3T. Which dbs can you access with Robo 3T? Maybe you can attach a screenshot of accessible databases, like you did with Studio 3T?

Hi,
On Robo 3T the issue is that, I can only see the DB I authenticate against `authdb`.
What I want to achieve is using `authdb` as `authSource` but explore explore `mydb`
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/561357/80001061-3c631300-84be-11ea-9273-bf1fa7f19b8d.png">
Here's a screencap, the only accessible database is the one I authenticate against, contrary to what Studio 3T is able to see/explore.

**Comment by anand-prem** [comment]
> > The only part that is not clear is the result in Robo 3T. Which dbs can you access with Robo 3T? Maybe you can attach a screenshot of accessible databases, like you did with Studio 3T?
> 
> Hi,
> On Robo 3T the issue is that, I can only see the DB I authenticate against `authdb`.
> What I want to achieve is using `authdb` as `authSource` but explore explore `mydb`
> <img alt="image" width="1268" src="https://user-images.githubusercontent.com/561357/80001061-3c631300-84be-11ea-9273-bf1fa7f19b8d.png">
> Here's a screencap, the only accessible database is the one I authenticate against, contrary to what Studio 3T is able to see/explore.

Any leads about this? Does this issue resolved?

**Comment by simsekgokhan** [comment]
@bbuivn Thanks a lot again for your great detailed problem report. 
Hi @anand-prem.
We have started to investigate. Seems to me that this is a known problem. 
Can you create those dbs (mydb and otherdb) manually and see if it works? (If this workaround solution works, this confirms that you have this known problem that we are trying to solve right now)

**Comment by quique0194** [comment]
I have only read permissions to the db, so creating manually the db doesn't always work

**Comment by simsekgokhan** [comment]
Hi @quique0194. Creating db on Robo 3T is an offline/independent operation. You should be able to create in any condition.

**Comment by simsekgokhan** [comment]
Hi @bbuivn, we have some fixes related to this problem in the new version.
I hope Robo 3T 1.4 will fix it -> [Robo 3T 1.4](https://github.com/Studio3T/robomongo/releases/tag/v1.4.0) 
Please let us know.

@quique0194 , I hope this will help you:  
New feature - Manually specify visible databases ->https://blog.robomongo.org/robo-3t-1-4/#a2

**Comment by bbuivn** [comment]
Hi @simsekgokhan 
I've tested Robo3T 1.4 and I can confirme that it does work like a charm with the box `Manually specify visible databases` ticked.
<img width="772" alt="image" src="https://user-images.githubusercontent.com/561357/93616117-97008c80-f9d4-11ea-90a0-a84edbfc3e3d.png">

I will add some details about the issue though.
This is an issue that looks related versions of MongoDB prior to 4.0 [see the explanation about `listDatabase` behavior](https://docs.mongodb.com/v4.0/reference/command/listDatabases/#behavior)

And indeed, from 4.0.6 there's no need to specify databases manually. You'll only need it on priori version (3.6 and prior).

Thanks a lot!
I will close this issue now :)

**Comment by simsekgokhan** [comment]
@bbuivn Thank you!
