### ISSUE TITLE
Failed to execute "listdatabases" command.

### ISSUE THREAD

**Issue by Mert1980** [Studio3T/robomongo#1699]
I am using the latest version of robo3t but I am not able to connect mongoDB at localhost
![Screenshot from 2019-12-31 22-45-33](https://user-images.githubusercontent.com/55088530/71635341-f4289800-2c23-11ea-84c2-c167db1fe49c.png)

**Comment by Mert1980** [comment]
Update: I filled in the authentication tab with my mongoDB username and password. It is working fine now!

**Comment by joch182** [comment]
In my case i just download the newest version of Robo3T from the website and now works fine.
