### ISSUE TITLE
not able to compile robo 3t under centos 7

### ISSUE THREAD

**Issue by saryayung** [Studio3T/robomongo#1731]
I am not able to compile robomongo project and it gives error as below.
gmake[2]: *** No rule to make target `/lib/x86_64-linux-gnu/libresolv.so.2', needed by `src/robomongo/robo3t'.  Stop.
Would someone gives a hint on the issue? Thanks!

**Comment by simsekgokhan** [comment]
Hi @saryayung, can you please share the full error output? 
Can you confirm you have that file `/lib/x86_64-linux-gnu/libresolv.so.2` on your system?

And fyi, our build steps are updated since we started to develop Robo 1.4.
