### ISSUE TITLE
macOS Catalina font rendering problems

### ISSUE THREAD

**Issue by nonagonal** [Studio3T/robomongo#1740]
Hi,

The font rendering on macOS Catalina on an external monitor looks strange:
![Screen Shot 2020-06-16 at 12 03 24 PM](https://user-images.githubusercontent.com/4778958/84798850-6ff78080-afc9-11ea-8cac-7b032ee26aac.png)

I found a few macOS font smoothing issues addressed in Qt  5.12:
https://bugreports.qt.io/browse/QTBUG-68824
https://bugreports.qt.io/browse/QTBUG-71946

I see that Robo 3T 1.3.1 ships with Qt 5.9.3. How often is the Qt library version upgraded? I'm hoping that'll fix the issue.

Regards,
Jeremy

**Comment by simsekgokhan** [comment]
Hi @nonagonal , thanks a lot for reporting the problem and sharing your suggestion.
We consider Qt upgrade (which is usually not simple) on every new Robo version depending on  the volume of UI problems reported by QA and users. 
Can you share full screenshot of your problem please?

**Comment by nonagonal** [comment]
Sure - I used to develop Qt applications and I know what you mean about it not being simple!

This is the screenshot on my laptop monitor (looks clear to me):
<img width="415" alt="laptop monitor" src="https://user-images.githubusercontent.com/4778958/86798362-b24b3500-c03e-11ea-8ede-5ab8bd83695a.png">

This is the screenshot on my external monitor (looks very bold and jagged, especially compared with other apps on this monitor):
![external monitor](https://user-images.githubusercontent.com/4778958/86798363-b2e3cb80-c03e-11ea-9b14-30030f112f2d.png)

It seems like github is rescaling the images but hopefully if you zoom into them you can see what I mean. I'm pretty sure this issue is what was described as fixed in Qt 5.12, but I'm not completely sure.

Let me know if I can provide any additional info. Thanks!

**Comment by simsekgokhan** [comment]
On Windows & macOS, we have upgraded our Qt version to 5.12.8 (Apr/2020).
I hope Robo 3T 1.4 will fix some of your problems -> [Robo 3T 1.4](https://github.com/Studio3T/robomongo/releases/tag/v1.4.0)

**Comment by nonagonal** [comment]
Yes - the fonts look great now! Thank you!
