### ISSUE TITLE
Unable to connect on localhost with 1.4 (Ubuntu 20.04, mongod 4.2.9)

### ISSUE THREAD

**Issue by jflebeau** [Studio3T/robomongo#1757]
Just tried the new relase and got this weird behavior: I can't use a direct connection to `localhost:27017` (it still works fine with 1.3.x).

![Screenshot from 2020-08-27 11-40-06](https://user-images.githubusercontent.com/5445635/91464131-39a47000-e85a-11ea-8d5e-ec0c40ecf980.png)

**Comment by vdemin** [comment]
Same here, but 127.0.0.1:27017 works. Arch Linux, mongodb 4.4.0

**Comment by jflebeau** [comment]
Haha didn't think about trying 127.0.0.1, working too.

**Comment by simsekgokhan** [comment]
Hi @jflebeau , @vdemin , thanks a lot for reporting the problem. We just released today officially, hopefully with the fix for this issue. Could you please make a quick check? https://robomongo.org/download

**Comment by jflebeau** [comment]
Yup, working.
