### ISSUE TITLE
Forget libstdc++.so.6.0.28 in release 1.4.0

### ISSUE THREAD

**Issue by tonal** [Studio3T/robomongo#1758]
In archive `robo3t-1.4.0-linux-x86_64-a61e33c.tar.gz` forget `libstdc++.so.6.0.28`
```
$ tar -tvzf robo3t-1.4.0-linux-x86_64-a61e33c.tar.gz | grep libstdc
lrwxrwxrwx gsimsek/gsimsek        0 2020-08-24 17:33 robo3t-1.4.0-linux-x86_64-a61e33c/lib/libstdc++.so.6 -> libstdc++.so.6.0.28
```
Hawe only link `libstdc++.so.6`

**Comment by simsekgokhan** [comment]
Hi @tonal , thanks a lot for reporting the problem. We just released today officially, hopefully with the fix for this issue.  
 
- Could you please check? https://robomongo.org/download 
- And were you able to use the app with this problem?

**Comment by tonal** [comment]
All Ok!
