### ISSUE TITLE
Version 1.4 in macOS with in dark mode seems weird

### ISSUE THREAD

**Issue by DimaRabkin** [Studio3T/robomongo#1763]
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/8135387/92324228-776a7b00-f048-11ea-9262-6e3834e7250d.png">

**Comment by rohitkhatri** [comment]
Having the same issue after updating to 1.4

**Comment by maxcanna** [comment]
This is duplicate of #1761

**Comment by DimaRabkin** [comment]
Closing due to duplication
