### ISSUE TITLE
UI looks like Windows 98 on macOS

### ISSUE THREAD

**Issue by levrik** [Studio3T/robomongo#1766]
After the upgrade to 1.4 the UI looks like Windows 98 on macOS.
I've already applied the workaround described in #1761 to disable the dark mode.
Also I checked the `Theme` selection in the `View` menu. `Native` and `Windows` looks exactly the same.
Using the `Fusion` theme for now since it doesn't look as terrible as the `Windows` theme does.

![image](https://user-images.githubusercontent.com/9491603/92358380-b13f8e00-f0e9-11ea-868b-ce19dfe41958.png)

**Comment by simsekgokhan** [comment]
Hi @levrik , thanks a lot for reporting this problem. We are now preparing a patch version 1.4.1 to fix this. 
It is still in pre-release state, but it will be great if you can make a quick test and let us know if it works.

Download the (pre-release) patch -> [Robo 1.4.1](https://github.com/Studio3T/robomongo/releases/tag/v1.4.1)

Horepfully, it should have the native look like this:  
<img src="https://user-images.githubusercontent.com/19390749/92695432-1c3ece00-f351-11ea-8e4e-44f4d2bdcbf2.jpg" width="600" />

**Comment by levrik** [comment]
Looks fine now. Thanks!
