### ISSUE TITLE
Dark theme is not visible

### ISSUE THREAD

**Issue by cloudwalker-technologies** [Studio3T/robomongo#1774]
Mac is on the Dark theme. Robo3t looks horrible on this theme.
<img width="640" alt="Pasted_Image_13_09_20__4_56_PM" src="https://user-images.githubusercontent.com/59967586/93016920-4955df80-f5e2-11ea-8be7-85efff13a645.png">

**Comment by mmarko0** [comment]
Yeah this made it awful to use. Using NightOwl as a temporary fix to force light mode for the app.

**Comment by Zak108** [comment]
Same is happening this side. Very difficult to read a lot of the content.

**Comment by cloudwalker-technologies** [comment]
I have intsalled this patched version, back to normal visiblity. 
https://github.com/Studio3T/robomongo/releases/tag/v1.4.1
