### ISSUE TITLE
robo3t - UI / Theme is messed on OSX

### ISSUE THREAD

**Issue by asoorm** [Studio3T/robomongo#1775]
After upgrade to: Robo 3T 1.4.0

<img width="703" alt="Screenshot 2020-09-14 at 11 44 57" src="https://user-images.githubusercontent.com/1465130/93076748-b8354600-f67f-11ea-802d-c5ddcd8202c4.png">

<img width="701" alt="Screenshot 2020-09-14 at 11 45 42" src="https://user-images.githubusercontent.com/1465130/93076808-d26f2400-f67f-11ea-90ae-ad4a6752eab7.png">

<img width="243" alt="Screenshot 2020-09-14 at 11 46 24" src="https://user-images.githubusercontent.com/1465130/93076880-ed419880-f67f-11ea-870b-c1995c1945cd.png">

Makes the Robo3t pretty unusable.

**Comment by dongdong7** [comment]
I have the same problem

**Comment by emrepirnaz** [comment]
+1

**Comment by nikhilmuz** [comment]
Were facing the same issue now the patch seems to work though it is light theme instead of dark preference on OS.

**Comment by justinmchase** [comment]
I am experiencing the same issue

**Comment by dstutzman-nt** [comment]
I believe this is a duplicate of #1761

**Comment by asoorm** [comment]
Patch 1.4.1 update seems to work fine. Thanks for quick fix

**Comment by dongdong7** [comment]
Thank you very much.

**Comment by justinmchase** [comment]
Its actually still broken in the sense that its not respecting the OS dark theme, the "fix" was to force it to always use the light theme it seems.

It is at least usable in this state but it should probably support the OS theme for this to be considered truly fixed.
