### ISSUE TITLE
Version 1.4+ doesn't work on fedora

### ISSUE THREAD

**Issue by alon710** [Studio3T/robomongo#1788]
I am trying to execute `/robo3t-1.4.1-linux-x86_64-122dbd9/bin/robo3t` and the output I get is 

> ./robo3t: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

**Comment by simsekgokhan** [comment]
Hi @alon710 , thanks for reporting the problem. But, unfortunately for Linux currently only Ubuntu is supported. 

Does this solve the problem as a workaround? -> https://github.com/Studio3T/robomongo/issues/1764#issuecomment-687823690

/ or 
` ln -s /usr/lib64/libcurl.so.4 ~/robo3t-1.4.1.../lib/libcurl-gnutls.so.4`

**Comment by alon710** [comment]
It does, thanks.
