### ISSUE TITLE
Failed to parse valid JSON with gtk2 theme

### ISSUE THREAD

**Issue by nicolasdscp** [Studio3T/robomongo#1847]
Hi,

I know the issue's name is unusual but there is a bug that I found just by switching the theme on `gtk2`.

 When I try to Create/Edit a document with the following JSON:

```json
{
    "a": 1,
    "b": ""
}
```
With the `gtk2` theme, i get the following error :

```
Unable to parse JSON:
Expecting '}' or ',', at (2, 12)
```

So i tried to switching the theme again to `normal` and it worked well with the default theme. I investigated and I found that the error appears only when I put a random type key after an `Int32` type key. Here's an example:

No error
```json
{
  "a": 1
}
```

No error
```json
{
  "b": "",
  "a": 1
}
```

Error because `b` is type `String` and it is after `a` which is type `Int32`
```json
{
   "c": false,
   "a": 1,
   "b": ""
}
```

```
Unable to parse JSON:
Expecting '}' or ',', at (3, 12).
```

Robo3T  1.4
```bash
$ robo3t --version
robo3t: /usr/bin/../lib/libcurl-gnutls.so.4: no version information available (required by robo3t)
MongoDB shell version v4.2.6-18-g6cdb6ab
git version: 6cdb6abcd43f9dba8f198d1e98deda432b894d7f
OpenSSL version: OpenSSL 1.0.2u  20 Dec 2019
allocator: tcmalloc
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64

```
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0.7
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
```

**Comment by simsekgokhan** [comment]
Hi, thanks for reporting the problem. Unfortunately, your OS is not supported. 
Please see: https://github.com/Studio3T/robomongo#supported-platforms
