### ISSUE TITLE
Monterey crash

### ISSUE THREAD

**Issue by chris-sadighgroup** [Studio3T/robomongo#1848]
Hello,

When i try to open my installed studio 3T (on Mac OS Monterey) it wont open.

When i try to open the last version of studio 3T (.dmg) from the website my mac instant crash

Any idea how to fix it ?

Thanks 

Regards

**Comment by codepope** [comment]
Hi, 

The issues pages here are for Robomongo/Robo3T only. Issues with Studio 3T should be reported on https://studio3t.com/feedback/ where they are tracked and managed. 

Thanks.
