### ISSUE TITLE
Options - Display Dates in - Local Timezone shows wrong date.

### ISSUE THREAD

**Issue by adamjmendoza** [Studio3T/robomongo#501]
Options - Display Dates in - Local Timezone shows wrong date.

Displaying dates in local time zone added + 17 instead of - 7 for my timezone. 

Robomongo version 0.8.4 on Windows 8.1 64bit.

**Comment by BradRuderman** [comment]
I am not sure when it is starting but it is now displaying incorrectly. I store the date in the server as UTC. My local client is set on Pacific time. 
Here is the info

Server:
```
"DateCreated" : ISODate("2015-02-28T19:06:42.000Z")
```

Shown
```
"DateCreated" : ISODate("2015-03-01T11:06:42.000+16:00"),
```

Computer is in the Mac OS X Latest Yosemite 10.10.2, set to Pacific Standard Time, syncing with Apple server. The correct time should covert to:

```
"DateCreated" : ISODate("2015-02-28T11:06:42.000-08:00"),
```

**Comment by SadBunny** [comment]
We can reproduce this problem on two different Windows 7 machines running Robomongo 0.8.4. Upgraded one to 0.8.5, still the same problem.

We're in Sydney, timezone AEST, which at the moment is at UTC (Zulu) +1100. I'm not exactly sure about when it changes to "wrong mode", but it's somewhere late in the evening or at night. Looking at the exact same record, between that time and until 11:00 (am) we get:

>     "DateTime" : ISODate("2015-03-*16*T11:00:00.000*-13:00*"),
![image](https://cloud.githubusercontent.com/assets/9690317/6743556/82890b9e-ceef-11e4-882e-e2c946827383.png)

... and after 11 am till at least late in the evening (I don't pull many all-nighters any more :) ) we get

>     "DateTime" : ISODate("2015-03-*17*T11:00:00.000*+11:00*"),
![image](https://cloud.githubusercontent.com/assets/9690317/6743753/66df3ed8-cef2-11e4-8e27-9efea175e302.png)

for the exact same record. Which in zulu mode always (not dependant on time of day) gives:

>     "DateTime" : ISODate("2015-03-17T00:00:00.000Z"),
![image](https://cloud.githubusercontent.com/assets/9690317/6743568/a576a5c6-ceef-11e4-97ea-62952f850075.png)

**Comment by stennie** [comment]
@SadBunny Thanks for the more specific info. I'm in Sydney as well fwiw ;)

**Comment by SadBunny** [comment]
@stennie So... Any ideas on how we can fix this? Or is just a bug in the Robomongo code that can be fixed? If you need any more tests, I'd be happy to oblige.

**Comment by stennie** [comment]
@SadBunny Assume it's just a bug in the code .. needs bandwidth for someone to look into it. My priority at the moment is getting the MongoDB 3.0 shell integrated for the Robomongo 0.9.0 milestone ;-).

**Comment by SadBunny** [comment]
@stennie Thanks, then I won't be looking at something in our environment causing it. (Which was possible, because apparently this cannot be reproduced everywhere, judging from earlier posts in this thread.) It's only a visual issue. Now off to the long and arduous task of explaining what UTC offsets are to our external tester from the UK :D

**Comment by SadBunny** [comment]
Issue is still causing a bunch of confusion around the place. any idea whether it's possible to fix this in a release in the foreseeable future?

**Comment by pwae** [comment]
Just re-iterating @SadBunny 's points. Same data, but using OS X (0.8.4), and having the same issue as well.

**Comment by dsernst** [comment]
Happening here: the local timezone option is displaying dates as `+16:00`, but my computer is set to `-8:00`.

**Comment by KuttKatrea** [comment]
I've detected this bug again in 0.9.0-RC10

**Comment by simsekgokhan** [comment]
Hi All,

There are some fixes related to timezone and date type on latest release Robomongo 1.0.
I hope it will solve some of your problems:
https://robomongo.org/download
http://blog.robomongo.org/robomongo-1-0/ -> section "c. Bug fixes"
