### ISSUE TITLE
$robomongo doesn't work - OS X 10.10.3 terminal

### ISSUE THREAD

**Issue by methodbox** [Studio3T/robomongo#887]
Is this not supported on Mac?  Terminal tools were supposed to launch robomongo.. I thought:

```
$ robomongo
-bash: robomongo: command not found
```

**Comment by anorsich** [comment]
@methodbox You can add something like this to the `.profile`:
```
alias robomongo="open -a Robomongo"
```
After this you should be able to run robomongo from terminal. 
But I agree, this is makes a lot of sense to be able to run robomongo from terminal out of the box.
